### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/kafka/conf'

### ISSUE THREAD

**Issue by AydinChavez** [bitnami/bitnami-docker-kafka#10]
Hi,

I get error in subject above when trying the latest bitnami kafka image via docker-compose.
I remember having a very similar error message with the mariadb-bitnami image some time ago. 
Is there any workaround or solution for this?

```
kafka_1      | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/kafka/conf'
zookeeper_1  | zookeep INFO  ==> Setting '-Xmx1024m -Xms1024mm' as heap size...
zookeeper_1  | nami    INFO  zookeeper successfully initialized
zookeeper_1  | INFO  ==> Starting zookeeper... 
zookeeper_1  | ZooKeeper JMX enabled by default
zookeeper_1  | Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
spark_kafka_1 exited with code 1
```
or once:
`kafka_1      | Error executing 'postInstallation': EACCES: permission denied, symlink '/opt/bitnami/kafka/conf' -> '/bitnami/kafka/conf'`

**Comment by AydinChavez** [comment]
For those who are affected:
Running
`sudo docker-compose run --user="root" --entrypoint chown kafka -R 1001 /bitnami` 
seem to help as a workaround.

**Comment by AydinChavez** [comment]
I give up, this container just does not work and inside it's a mess. 
Even the conf folders inside it reference themselves via symbolic links in a cyclic manner:

```
I have no name!@916258e76275:/bitnami/kafka$ ls -al /bitnami/kafka/conf 
lrwxrwxrwx 1 1001 root 23 Mar 27 15:11 /bitnami/kafka/conf -> /opt/bitnami/kafka/conf

I have no name!@916258e76275:/opt/bitnami/kafka$ ls -al conf
lrwxrwxrwx 1 1001 root 19 Mar 27 15:11 conf -> /bitnami/kafka/conf

```
This means:
`/bitnami/kafka/conf`  points to` /opt/bitnami/kafka/conf `
and
`/opt/bitnami/kafka/conf` points to `/bitnami/kafka/conf  `

**Comment by carrodher** [comment]
I am no able to reproduce the issue:
```
I have no name!@a20278c90719:/$ ls -la /opt/bitnami/kafka
...
lrwxrwxrwx 1 1001 root    19 Mar 28 08:43 conf -> /bitnami/kafka/conf
lrwxrwxrwx 1 1001 root    23 Mar 28 08:43 config -> /opt/bitnami/kafka/conf
lrwxrwxrwx 1 1001 root    19 Mar 28 08:43 data -> /bitnami/kafka/data
...
```

You're right that `/opt/bitnami/kafka/conf` points to `/bitnami/kafka/conf`, it is a common practice in Bitnami containers due to compatibility with cloud images and installers.

But, the reverse loop is not present (at least in the default container without modifications):
```
I have no name!@a20278c90719:/$ ls -la /bitnami/kafka
...
-rw-r--r-- 1 1001 root    0 Mar 28 08:43 .initialized
drwxr-xr-x 3 1001 root 4096 Mar 28 08:43 conf
drwxr-xr-x 2 1001 root 4096 Mar 28 08:43 data
```
`/bitnami/kafka/conf` is not pointing to another directory, it is the directory where the configuration is included:
```
I have no name!@a20278c90719:/$ ls -la /bitnami/kafka/conf/
drwxr-xr-x 2 1001 root 4096 Mar 28 08:43 certs
-rw-rw-r-- 1 1001 root  906 Mar 28 08:43 connect-console-sink.properties
-rw-rw-r-- 1 1001 root  909 Mar 28 08:43 connect-console-source.properties
-rw-rw-r-- 1 1001 root 5807 Mar 28 08:43 connect-distributed.properties
-rw-rw-r-- 1 1001 root  883 Mar 28 08:43 connect-file-sink.properties
-rw-rw-r-- 1 1001 root  881 Mar 28 08:43 connect-file-source.properties
-rw-rw-r-- 1 1001 root 1111 Mar 28 08:43 connect-log4j.properties
-rw-rw-r-- 1 1001 root 2730 Mar 28 08:43 connect-standalone.properties
-rw-rw-r-- 1 1001 root 1221 Mar 28 08:43 consumer.properties
-rw-rw-r-- 1 1001 root 4727 Mar 28 08:43 log4j.properties
-rw-rw-r-- 1 1001 root 1919 Mar 28 08:43 producer.properties
-rw-rw-r-- 1 1001 root 6822 Mar 28 08:43 server.properties
-rw-rw-r-- 1 1001 root 1032 Mar 28 08:43 tools-log4j.properties
-rw-rw-r-- 1 1001 root 1023 Mar 28 08:43 zookeeper.properties
```

Are you modifying something before start/up the container? I am using kafka 1.0.1-r2 released 5 days ago.

**Comment by AydinChavez** [comment]
Thanks for your answer. No I did not modify anything. I used the latest tag, which points also to  1.0.1-r2

**Comment by andresmgot** [comment]
My two cents is that your Kafka volume is corrupted. `docker-compose down -v` or manually deleting the volume should fix the issue.

**Comment by holms** [comment]
Not sure if my issue is related but still

```
holms@debian ~/D/c/l/a/prod> docker --tls service logs 8w1u11r5dlv5
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | 
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | Welcome to the Bitnami zookeeper container
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | 
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | WARN  ==> You set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | nami    INFO  Initializing zookeeper
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | zookeep INFO  ==> No injected configuration files found. Creating default config file...
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | zookeep INFO  ==> Setting '-Xmx1024m -Xms1024mm' as heap size...
dbs_zookeeper.1.8w1u11r5dlv5@swarm-slave-1    | Error executing 'postInstallation': EACCES: permission denied, scandir '/bitnami/zookeeper/data
```

**Comment by carrodher** [comment]
It seems an issue related to the volume and the non-root configuration. This container is a non-root container image that adds an extra layer of security and is generally recommended for production environments. However, because it runs as a non-root user, privileged tasks are typically off-limits.

Non-root containers also have some disadvantages when used for local development, Docker mounts host volumes preserving the host UUID and GUID. This can lead to permission conflicts with non-root containers, as the user running the container may not have the appropriate privileges to write to the host volume.

You can find more information checking those links:
 - https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/
 - https://docs.docker.com/engine/security/security/

How are you mounting the volume? Can you share with us more information about your deployment?

**Comment by holms** [comment]
Simple as this:

```
version: '3.7'
x-placement:
     &default-placement
     constraints:
       - node.role == worker
     preferences:
       - spread: node.role == worker

services:

  redis:
    image: redis:3-alpine
    networks:
      - redis
    deploy:
      mode: replicated
      replicas: 2
      placement: *default-placement

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
        - zookeeper:/bitnami/zookeeper
    deploy:
      placement: *default-placement

  kafka:
    image: 'bitnami/kafka:0'
    networks:
      - zookeeper
      - kafka
    volumes:
      - kafka:/bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    deploy:
      placement: *default-placement

volumes:
  zookeeper:
    driver: rexray
  kafka:
    driver: rexray

networks:
  redis:
    driver: overlay
  kafka:
    driver: overlay
  zookeeper:
    driver: overlay

```
