### ISSUE TITLE
I'm running latest kafka and I think there is issue with internal_protocol

### ISSUE THREAD

**Issue by jeeftor** [bitnami/bitnami-docker-kafka#108]
```
kafka_1      |  17:48:35.27
kafka_1      |  17:48:35.27 Welcome to the Bitnami kafka container
kafka_1      |  17:48:35.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka_1      |  17:48:35.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka_1      |  17:48:35.27
kafka_1      |  17:48:35.28 INFO  ==> ** Starting Kafka setup **
kafka_1      |  17:48:35.35 INFO  ==> Initializing Kafka...
kafka_1      |  17:48:35.35 INFO  ==> No injected configuration files found, creating default config files
kafka_1      | /opt/bitnami/scripts/libkafka.sh: line 496: internal_protocol: unbound variable
kafka_kafka_1 exited with code 1
```

```
  kafka:
    image: bitnami/kafka:latest

    networks:
      - global-kafka-network
    ports:
      # - '9092'
      # - "9092:9092" # Internal Port
      #- "29092:9092"
      #  - "19092:19092" # Local Port
      - "29092:29092" # Local Network Port
#      - "39092:39092" # Tunnel Network Port
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_SSL://kafka:9092,SASL_SSL_EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://kafka:9092,SASL_SSL_EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SASL_SSL_EXTERNAL:SASL_SSL,SASL_SSL:SASL_SSL


      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_INTER_BROKER_USER=interuser
      - KAFKA_INTER_BROKER_PASSWORD=interpassword
      - KAFKA_BROKER_USER=kafka
      - KAFKA_BROKER_PASSWORD=kafka_password
      - KAFKA_CERTIFICATE_PASSWORD=password

    depends_on:
      - zookeeper
    volumes:
      - ./config/:/bitnami/kafka/config/:ro
```
This error is not present in: `2.5.0-debian-10-r49`

**Comment by juan131** [comment]
Hi @jeeftor 

Thanks for reporting the issue. I created a PR to address the issue with unbound variables.

On the other hand, please take look to the sections below:

- https://github.com/bitnami/bitnami-docker-kafka#250-debian-10-r51
- https://github.com/bitnami/bitnami-docker-kafka#accessing-kafka-with-internal-and-external-clients
- https://github.com/bitnami/bitnami-docker-kafka#security

Several changes were introduced in the `2.5.0-debian-10-r49` to allow more flexibility in the way to configure listeners and authentication.

According to the new changes, you need to adapt your Docker Compose as shown below:

```
  kafka:
    image: bitnami/kafka:latest
    networks:
      - global-kafka-network
    ports:
      - "29092:29092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_INTER_BROKER_USER=interuser
      - KAFKA_INTER_BROKER_PASSWORD=interpassword
      - KAFKA_CLIENT_USER=kafka
      - KAFKA_CLIENT_PASSWORD=kafka_password
      - KAFKA_CERTIFICATE_PASSWORD=password

    depends_on:
      - zookeeper
    volumes:
      - ./config/:/bitnami/kafka/config/:ro
```
