### ISSUE TITLE
Change location and name of keystore and truststore

### ISSUE THREAD

**Issue by Graeme-B** [bitnami/bitnami-docker-kafka#113]
I'm trying to change the name and location of the keystore and truststore. My compose file looks like this
```
 kafka1:
   image: bitnami/kafka:latest
   hostname: kafka1
   ports:
     - "9092:9092"
     - "9093:9093"
   volumes:
     - /xxx:/xxx
     - /k:/bitnami/kafka
   environment:
     ALLOW_PLAINTEXT_LISTENER: "yes"
     KAFKA_CFG_BROKER_ID: 1
     KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL_HOST:SSL"
     KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,SSL_HOST://:9093"
     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://docker1:9092,SSL_HOST://docker1:9093"
     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
     KAFKA_CERTIFICATE_PASSWORD: "Testing1234"
     KAFKA_CFG_PROTOCOL: "TLS"
     KAFKA_CFG_SSL_PROTOCOL: "TLS"
     KAFKA_CFG_SSL_ENABLED_PROTOCOLS: "TLSv1.2,TLSv1.1,TLSv1"
     KAFKA_CFG_SSL_KEYSTORE_PASSWORD: "Testing1234"
     KAFKA_CFG_SSL_KEYSTORE_LOCATION: "/xxx/keystore.jks"
     KAFKA_CFG_SSL_KEY_PASSWORD: "Testing1234"
     KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: "Testing1234"
     KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: "/xxx/truststore.jks"
     KAFKA_CFG_SSL_CLIENT_AUTH: "required"
     KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
     KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_CFG_LOG_RETENTION_HOURS: 745
   networks:
     - kafka-net
```
When I try to start the container, I get the message

`ERROR ==> In order to configure the TLS encryption for Kafka you must mount your kafka.keystore.jks and kafka.truststore.jks certificates to the /bitnami/kafka/config/certs directory.`

If I set the volume and keystore/truststore name and location according to the message - ie I change the name of the keystore and truststore, and mount the volume with `- /xxx:/bitnami/kafka/config/certs` - then the container starts. If I open a command prompt on the running container, I can see the properties file contains my password, so the properties file is being created with my parameters: so why doesn't this work with my changed locations?

Many thanks,

Graeme
