### ISSUE TITLE
Add to the readme information about running zookeeper on a different port

### ISSUE THREAD

**Issue by yurii-sio2** [bitnami/bitnami-docker-kafka#118]
**Description**

There is no information in the readme file about running zookeeper on a different port. It's not obvious how to do that without searching on the Internet and reading some other info sources that readme.

**Steps to reproduce the issue:**

no steps

**Describe the results you received:**

-

**Describe the results you expected:**

Information is added to the readme file.

To run zookeeper on different port, you should set `ZOO_PORT_NUMBER` environment variable and then set this port to the kafka broker.

```
services:
  zookeeper-server:
    ...
    ports:
      - '**3777**:**3777**'
    environment:
      - ZOO_PORT_NUMBER=**3777**

  kafka-server:
    ...
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:**3777**
```
