### ISSUE TITLE
JMX not working? Important

### ISSUE THREAD

**Issue by knokio** [bitnami/bitnami-docker-kafka#119]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

I'm trying to monitor Kafka using JMX but it's not exposing anything.
Used the refered "JMX_PORT" environment variable but does not seem to do anything.

Searched for "JMX_PORT" in the repository and there's no reference to it.
#22 See for related issue

**Steps to reproduce the issue:**

1. docker-compose or docker run with `JMX_PORT=9000` defined 
2. Try to retrieve JMX information but no response

**Describe the results you received:**

**Version**

bitnami/kafka:2.3.0

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-3-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.92GiB
 Name: kafka-core0_prod-europe
 ID: KFFR:R2XM:WIJN:FEQP:EKYZ:VH7I:N7WN:A36I:FLVY:PPKQ:5OLQ:2P3M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- AWS

**Comment by andresbono** [comment]
Hi @knokio, how are you checking JMX? We tried with `JMX_PORT=9000` and we can see the port listening and the process started with the JMX options:

```
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9000
```

You can check on your side with `ps aux | grep java`

**Comment by knokio** [comment]
Hi @andresbono thanks for helping.

ps aux | grep java
```
eos      17839  2.6 50.2 4151220 1010928 ?     Ssl  Jun01 2222:42 java -Xmx1G -Xms128M -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true -Xloggc:/opt/bitnami/kafka/bin/../logs/kafkaServer-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9000 ..
```
```
$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::9010                 :::*                    LISTEN      17802/docker-proxy
tcp6       0      0 :::9000                 :::*                    LISTEN      17815/docker-proxy
```

It's seems to be in fact running and netstat also exposes it.
I tried to connect to it from different tools, locally and remote but can't retrieve any JMX response.

Any other way to check if it's working? Either trough a CLI or Telnet or other option?

**Comment by andresbono** [comment]
Hi @knokio, I don't know about specific clients to check that. How do you plan to consume JMX metrics?

**Comment by knokio** [comment]
> Hi @knokio, I don't know about specific clients to check that. How do you plan to consume JMX metrics?

I tried with Datadog Agent (as I do with other applications), with jmxcli, jmxterm but none of them can connect.

**Comment by marcosbc** [comment]
Hi @knokio, sorry for the delay, as this issue seems to have gotten lost in our ticket tracking system.

As for the issue, it looks like what can be happening is that JMX does not play nice with the Docker network proxy.

In order to get it working, you would need to connect directly to the IP the container is running in. To get that value, run `docker inspect CONTAINER_NAME` and look for "IPAddress".

Once you have the IP, you should be able to `curl` to the address and see a result like the below:

```
$ curl 172.31.0.3:9000
curl: (52) Empty reply from server
```

But if you see this, it means you used a wrong IP:

```
$ curl localhost:9000
curl: (56) Recv failure: Connection reset by peer
```

It does not look like JMX to allow requests from any IP address (by binding to 0.0.0.0), so either you put your monitoring software in Docker containers in the same network, or you'll need to obtain the very specific IP address for the Kafka node.

If you want something more suited for production, you can always take a look at the [Bitnami Kafka chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka) for Kubernetes. It includes JMX Exporter for Prometheus, and if that does not work for you, you should be shown internal hostname after deploying that you can use for connecting to Kafka/JMX.

**Comment by knokio** [comment]
Thanks for your reply @marcosbc - I'll try those. 
Can you think of a workaround?

**Comment by marcosbc** [comment]
@knokio After trying this again, I could get it working by making these changes to the original docker-compose file (present in this repo):

```
   kafka:
     image: 'docker.io/bitnami/kafka:2-debian-10'
     ports:
+      - '9000:9000'
       - '9092:9092'
     volumes:
       - 'kafka_data:/bitnami'
     environment:
       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
       - ALLOW_PLAINTEXT_LISTENER=yes
+      - JMX_HOSTNAME=0.0.0.0
+      - JMX_PORT=9000
     depends_on:
       - zookeeper
```

Could you try those changes and see if it works?

**Comment by knokio** [comment]
I'll try them today or tomorrow! @marcosbc thank you

**Comment by juan131** [comment]
Friendly reminder @knokio

**Comment by JoaoPPinto** [comment]
Hello @marcosbc and @juan131 , I took over from @knokio and looked into this as he is currently out-of-office.

Forwarding the JMX_PORT in the compose ports seems to do the trick. I could get metrics from the kafka container connecting to the JMX port using as hostname the container IP address and `localhost`. Connections that use an external DNS name or IP address as hostname result in a connection timeout.

Datadog is also consuming metrics from JMX, so I think this issue can be closed.

Thanks for your assistance

**Comment by andresbono** [comment]
Thank you very much for the confirmation @JoaoPPinto.

**Comment by JoaoPPinto** [comment]
Hello again,

I've had some time to look into this some more, specifically try to connect to kafka through JMX from a remote host.
I've found that two additional java options are necessary, namely `-Dcom.sun.management.jmxremote.rmi.port=<PORT>`
and `-Djava.rmi.server.hostname=<ADDRESS>`. 

From what I could gather, setting `com.sun.management.jmxremote.port=$JMX_PORT` publiches an RMI Connect for local access, and a second RMI connecter in a read-only registry on the port specified in `com.sun.management.jmxremote.rmi.port=<PORT>`. [1]

The second property I believe has to do with Remot Stub Objects used by RMI, which contain the server address for later use during execution.

Setting both these in the docker compose through the `KAFKA_OPTS` environment variable does the trick (though I'm not entirely sure this is the correct variable, the kafka init scripts use a `KAFKA_JMX_OPTS` that gets populated with some default values if not previously defined, and then if JMX_PORT is defined appends the jmxremote.port config)

It seems these are some rather common pitfalls with Java RMI, but I figured I should share these here in case someone bumps into a similar issue.

Again, thanks for your assitance with this issue

[1] - https://docs.oracle.com/javase/9/management/monitoring-and-management-using-jmx-technology.htm#JSMGM-GUID-F08985BB-629A-4FBF-A0CB-8762DF7590E0

**Comment by juan131** [comment]
Thanks so much for sharing you insights @JoaoPPinto!!

As @marcosbc said on a previous comment, we're using a similar approach to expose JMX metrics in the [Kafka chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka). As you can see in the [statefulset definition](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml), we're adding the `JMX_PORT` env. variable:

```yaml
            - name: JMX_PORT
              value: "5555"
```

And then, we're using a [JMX exporter container](https://github.com/bitnami/bitnami-docker-jmx-exporter) to gather and transform these metrics into something that can be consumed by Prometheus.

**Comment by gtato** [comment]
I am a bit confused. Why doesn't this kafka image use the [jmx_exporter](https://github.com/prometheus/jmx_exporter)? I tried to specify it using KAFKA_OPTS like in the wurstmeister/kafka-docker image but it gives some manifest error. If you use an external exporter, i don't get how you specify the jmx port on that. Why does this have to be so messy, monitoring kafka is a basic funcationality!

**Comment by juan131** [comment]
Sorry I didn't explain myself correctly @gtato 

It uses the JMX exporter, but the Kafka chart also uses this [JMX exporter container](https://github.com/bitnami/bitnami-docker-jmx-exporter) which basically gather the JMX metrics from Kafka and adapts them into [PromQL syntax](https://prometheus.io/docs/prometheus/latest/querying/basics/) so they can be consumed by Prometheus. This is something very specific for Kubernetes.

If you are not running Kafka on K8s and you're not interesting on using Prometheus to monitor Kafka, you can simply define the environment variable **JMX_PORT**, and it should expose the JMX metrics.

**Comment by gtato** [comment]
Hey Juan, thanks for the answer. 

I am not using k8s for the moment, but i am want to monitor kafka using prometheus/grafana. In various articles online this is done by using the jmx_exporter agent jar within the kakfa image by specifying the env KAFKA_OPTS=-javaagent:jmx_exporter_agent:port:config.yml (and this agent is already compatible with prometheus). However, with bitnami image this does not work. 

I just wanted to avoid an extra container just for exporting JMX metrics, but let's say for a moment that I want to use it. Does this have anything to do with JMX_PORT? Should this container be configured to access that port on the kafka container or it is not related?

**Comment by juan131** [comment]
Hi @gtato 

As you can see at the line below, this image uses the `kafka-server-start.sh` script to start Kafka

- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/kafka/run.sh#L28

If we inspect this script, it's indeed a wrapper that executes the `kafka-run-class.sh` script. So, if we inspect his second script we find the piece of code below:

```bash
# JMX settings
if [ -z "$KAFKA_JMX_OPTS" ]; then
  KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false "
fi

# JMX port to use
if [  $JMX_PORT ]; then
  KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT "
fi
```

So.. Basically when setting the `JMX_PORT` environment variable without setting the `KAFKA_JMX_OPTS`, you're actually appending the options `-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.port=$JMX_PORT` to Kafka.

If you want to use different options, you just need to set the `KAFKA_JMX_OPTS` with your own ones.

**Comment by gowrisankar22** [comment]
@juan131 it dint work for me
```
version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
      - '9000:9000'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=9000
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9000
    depends_on:
      - zookeeper
  jmx-exporter:
    image: docker.io/bitnami/jmx-exporter:0-debian-10
    ports:
      - 5556:5556
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

**Comment by andresbono** [comment]
Hi @gowrisankar22, what are you trying to achieve? Please note the following service bindings:

- kafka container is binding port 9000 (JMX protocol) as per your configuration. If you do a curl to this port, it is expected to get the error "Empty reply from server", because jmx protocol is not compatible with http.

```console
$ docker-compose exec kafka curl localhost:9000
curl: (52) Empty reply from server
```

- jmx-exporter is binding port 5556 (http, [PromQL syntax](https://prometheus.io/docs/prometheus/latest/querying/basics/)). This is exposing Prometheus metrics, you can do a curl and get a result:

```console
$ docker-compose exec jmx-exporter curl localhost:5556/metrics
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.14.0",name="jmx_prometheus_httpserver",} 1.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.004124319
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 1.0
# HELP jmx_scrape_cached_beans Number of beans with their matching rule cached
# TYPE jmx_scrape_cached_beans gauge
jmx_scrape_cached_beans 0.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
```

However, note that the JMX exporter is using an example configuration file, so it is not actually connecting to the Kafka container. You will need to create a valid configuration file and mount it in the container. You can see the configuration options here: https://github.com/prometheus/jmx_exporter#configuration, and you can also check the Kafka Helm Chart templates as an example: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/jmx-configmap.yaml

**Comment by gowrisankar22** [comment]
@andresbono I tried that already but it is not working..

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "java"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at io.prometheus.jmx.WebServer.main(WebServer.java:21)
```

jmxexporter docker-compose file:

```
jmxexporter:
    image: docker.io/bitnami/jmx-exporter:0.13.0-debian-10-r73
    container_name: jmxexporter
    volumes:
    - /root/jmx_exporter.yml:/opt/bitnami/jmx-exporter/jmx_exporter.yml
    ports:
      - 5556:5556
    command: java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm -jar jmx_prometheus_httpserver.jar 5556 /opt/bitnami/jmx-exporter/jmx_exporter.yml
```

**Comment by andresbono** [comment]
Splitting the full command into two pieces (`entrypoint` and `command`) can make the trick:

```yaml
jmxexporter:
    image: docker.io/bitnami/jmx-exporter:0.13.0-debian-10-r73
    container_name: jmxexporter
    volumes:
    - /root/jmx_exporter.yml:/opt/bitnami/jmx-exporter/jmx_exporter.yml
    ports:
      - 5556:5556
    entrypoint: java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm -jar jmx_prometheus_httpserver.jar
    command: 5556 /opt/bitnami/jmx-exporter/jmx_exporter.yml
```

Note the `ENTRYPOINT` and `CMD` in the [Dockerfile](
https://github.com/bitnami/bitnami-docker-jmx-exporter/blob/a73b3c677f2f1de5dac1cb6fe7db058949c35d0c/0/debian-10/Dockerfile#L32-L33) of bitnami/jmx-exporter.

`command` in the docker-compose is overwriting only the CMD so `jmx_prometheus_httpserver.jar` is trying to parse `java` as the first argument passed, which is expected to be a port number.

**Comment by gowrisankar22** [comment]
@andresbono after splitting with `ENTRYPOINT` and `CMD` at least the above exception fixed but actual problem not. It is still not able to scrape the kafka jmx metrics.

I have tried all the Kafka from here
https://github.com/prometheus/jmx_exporter/tree/master/example_configs

and also from here 
https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/jmx-configmap.yaml

but what I get is only below,
```
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.13.0",name="jmx_prometheus_httpserver",} 1.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.117287166
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 1.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
```

**Comment by andresbono** [comment]
Are you getting the `SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 127.0.0.1;` error showing in the logs?

If you want, please share the current docker-compose and jmx configuration yaml so that we can try to reproduce the issue.

**Comment by gowrisankar22** [comment]
@andresbono  yes right.. Please find the docker-compose file and JMX-exporter configuration below,
```
version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
      - '5555:5555'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=5555
      #- KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555
    depends_on:
      - zookeeper
  jmxexporter:
    image: docker.io/bitnami/jmx-exporter:0.13.0-debian-10-r73
    container_name: jmxexporter
    volumes:
    - /Users/i307955/new/jmx_exporter_2.yml:/opt/bitnami/jmx-exporter/jmx_exporter_new.yml
    ports:
      - 5556:5556
    entrypoint: java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm -jar jmx_prometheus_httpserver.jar
    command: 5556 /opt/bitnami/jmx-exporter/jmx_exporter_new.yml
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

jmx_exporter_new.yml
```
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
ssl: false
whitelistObjectNames: ["kafka.controller:*","kafka.server:*","java.lang:*","kafka.network:*","kafka.log:*"]
rules:
  - pattern: kafka.controller<type=(ControllerChannelManager), name=(QueueSize), broker-id=(\d+)><>(Value)
    name: kafka_controller_$1_$2_$4
    labels:
      broker_id: "$3"
  - pattern: kafka.controller<type=(ControllerChannelManager), name=(TotalQueueSize)><>(Value)
    name: kafka_controller_$1_$2_$3
  - pattern: kafka.controller<type=(KafkaController), name=(.+)><>(Value)
    name: kafka_controller_$1_$2_$3
  - pattern: kafka.controller<type=(ControllerStats), name=(.+)><>(Count)
    name: kafka_controller_$1_$2_$3
  - pattern: kafka.server<type=(ReplicaFetcherManager), name=(.+), clientId=(.+)><>(Value)
    name: kafka_server_$1_$2_$4
    labels:
      client_id: "$3"
  - pattern : kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
    name: kafka_network_$1_$2_$4
    labels:
      network_processor: $3
  - pattern : kafka.network<type=(RequestMetrics), name=(RequestsPerSec), request=(.+)><>(Count)
    name: kafka_network_$1_$2_$4
    labels:
      request: $3
  - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>(Count|OneMinuteRate)
    name: kafka_server_$1_$2_$4
    labels:
      topic: $3
  - pattern: kafka.server<type=(DelayedOperationPurgatory), name=(.+), delayedOperation=(.+)><>(Value)
    name: kafka_server_$1_$2_$3_$4
  - pattern: kafka.server<type=(.+), name=(.+)><>(Count|Value|OneMinuteRate)
    name: kafka_server_$1_total_$2_$3
  - pattern: kafka.server<type=(.+)><>(queue-size)
    name: kafka_server_$1_$2
  - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
    name: java_lang_$1_$4_$3_$2
  - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
    name: java_lang_$1_$3_$2
  - pattern : java.lang<type=(.*)>
  - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
    name: kafka_log_$1_$2
    labels:
      topic: $3
```

**Comment by helloworlde** [comment]
If kafka run in docker, need add remote config properties, and it works for me:

```yaml
version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    hostname: host.docker.internal
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=9999
      - KAFKA_JMX_OPTS=-Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    depends_on:
      - zookeeper
```
