### ISSUE TITLE
Can't set up production kafka image with docker-compose.yml. kafka_jaas.config missing.

### ISSUE THREAD

**Issue by Kudze** [bitnami/bitnami-docker-kafka#120]
**Description**

I've tried to follow the examples at README.md but can't successfully start kafka with SASL_SSL, with external and client listeners. 

**Steps to reproduce the issue:**

1. docker-compose.yml (I've stripped credentials & server ip from docker-copose.yml)

```
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka_zookeeper_user
      - ZOO_SERVER_PASSWORDS=somezookeeperpassword
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    volumes:
      - /root/kafka-docker/volume-persistance:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SSL,EXTERNAL:SASL_SSL
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://<server IP here>:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CLIENT_USER=kafka_user
      - KAFKA_CLIENT_PASSWORD=someuserpasswordhere
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka_zookeeper_user
      - KAFKA_ZOOKEEPER_PASSWORD=somezookeeperpassword
      - KAFKA_CERTIFICATE_PASSWORD=mycertpassword
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    ports:
      - '9092:9092'
      - '9093:9093'
    depends_on:
      - zookeeper
```

2. I generated certificate files with using this script: https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh
3. I placed kafka.truststore.jks and kafka.keystore.jks under `/root/kafka-docker/volume-persistance/config/certs/` directory.

**Describe the results you received:**

kafka shuts down with exception. (It complains about `/opt/bitnami/kafka/config/kafka_jaas.conf` I couldn't find any documentation on this file on README.md) No file exists at `/root/kafka-docker/volume-persistance/config/kafka_jaas.conf`

The exception:

```

kafka_1      | [2020-07-29 13:48:48,812] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
kafka_1      | [2020-07-29 13:48:52,584] INFO [SocketServer brokerId=1001] Created data-plane acceptor and processors for endpoint : EndPoint(null,9092,ListenerName(CLIENT),SSL) (kafka.network.SocketServer)
kafka_1      | [2020-07-29 13:48:52,586] INFO Awaiting socket connections on 0.0.0.0:9093. (kafka.network.Acceptor)
kafka_1      | [2020-07-29 13:48:52,603] ERROR [KafkaServer id=1001] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1      | java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'external.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /opt/bitnami/kafka/config/kafka_jaas.conf
kafka_1      |  at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:133)
kafka_1      |  at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:98)
kafka_1      |  at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:70)
kafka_1      |  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:131)
kafka_1      |  at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:97)
kafka_1      |  at kafka.network.Processor.<init>(SocketServer.scala:724)
kafka_1      |  at kafka.network.SocketServer.newProcessor(SocketServer.scala:367)
kafka_1      |  at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:252)
kafka_1      |  at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:251)
kafka_1      |  at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:214)
kafka_1      |  at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:211)
kafka_1      |  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1      |  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1      |  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1      |  at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:211)
kafka_1      |  at kafka.network.SocketServer.startup(SocketServer.scala:122)
kafka_1      |  at kafka.server.KafkaServer.startup(KafkaServer.scala:266)
kafka_1      |  at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
kafka_1      |  at kafka.Kafka$.main(Kafka.scala:82)
kafka_1      |  at kafka.Kafka.main(Kafka.scala)
kafka_1      | [2020-07-29 13:48:52,618] INFO [KafkaServer id=1001] shutting down (kafka.server.KafkaServer)

```

**Describe the results you expected:**

I expect for kafka docker to run successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

No additional info provided

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 21
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-40-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.894GiB
 Name: GKIO
 ID: AGL4:F2JU:C2OY:O3BQ:GQL5:5WCX:F62R:GUGA:OJ35:TRA2:GMSV:3CUF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
