### ISSUE TITLE
Kafka SSL error

### ISSUE THREAD

**Issue by Graeme-B** [bitnami/bitnami-docker-kafka#122]
I'm trying to set up an SSL-secured Kafka network on three nodes, using the Bitnami Docker image. I'm running Docker 19.03.11 and Bitnami Kafka version 2.5.0-r10 on all servers.

I have got this working on one three node cluster, but I'm having problems getting this to run on a second three node cluster.
The error message I see is "Failed authentication with /10.255.0.2 (SSL handshake failed)" when I try to start the first Kafka node
and "Failed authentication with /10.255.0.6 (SSL handshake failed)" when I try to start the second Kafka node: the third node starts successfully. However, the IP addresses 10.255.0.2 and 10.255.0.6 are assigned to the ingress-sbox containers, which appear to be internal to Docker - these are part of the ingress network, and disappear when the stack is closed down. 

So, why do two Kafka servers attempting to create an SSL connection with this container whilst the other Kafka server works?
Why does this only happen on one cluster (the docker-compose files are identical save for the server names)?
How do I get more information about this error?
Finally, how do I either stop this connection from being made, or set up the SSL parameters to allow the connection to be made successfully?

All help gratefully received!

**Comment by dani8art** [comment]
Hi @Graeme-B thank you for opening this issue

Could you share with us your docker-compose.yaml so we can try to reproduce it on our environment? 

> How do I get more information about this error?

Additionally, you can add `BITNAMI_DEBUG=true` and more detailed logs will be shown.

**Comment by Graeme-B** [comment]
@dani8art unfortunately it's on a network which I can't access externally, so I can't easily share the docker-compose file. I'll try to find a way to export it.

In the meantime, I'll try setting the debug flag - I guess it's in the environment section?

Thanks,

Graeme

**Comment by Graeme-B** [comment]
@dani8art the docker compose file is enclosed
[docker-compose.yml.txt](https://github.com/bitnami/bitnami-docker-kafka/files/5034087/docker-compose.yml.txt)
, with server names and passwords changed. There may be typos as I had to retype the data.

**Comment by dani8art** [comment]
Hi @Graeme-B please could you also share how you are creating and setting up the SSL volumen? I'm getting this error from your compose

```console
kafka1_1  |  09:56:17.08 ERROR ==> In order to configure the TLS encryption for Kafka you must mount your kafka.keystore.jks and kafka.truststore.jks certificates to the /bitnami/kafka/config/certs directory.
```

**Comment by Graeme-B** [comment]
Hi @dani8art 

I have the keystore and truststore, called **kafka.keystore.jks** and **kafka.truststore.jks**, on the /Certificates directory which is mapped in the docker-compose.yml to **/bitnami/kafka/config/certs** on all three servers. Each server has its own individual keystore, which identifies that server. These files are world readable. I can't copy the certificates to this issue as they're on a separate server (and they wouldn't be much use anyway, as they identify my particular servers!)

Thanks,

Graeme

**Comment by dani8art** [comment]
Hi @Graeme-B sorry, I didn't explain well, I didn't want you to share your own files but you explaining how did you create them so that I can follow the process in order to reproduce your environment. Could you please add this info?

**Comment by Graeme-B** [comment]
Hi @dani8art, 

No problem - I've enclosed a shell script. This actually creates four server certificates for servers named docker1 to docker4. I then rename the certificates to kafka.keystore.jks for each server (and kafka.truststore.jks for the truststore, which is shared between all servers).

Graeme
[mkcerts.sh.txt](https://github.com/bitnami/bitnami-docker-kafka/files/5041041/mkcerts.sh.txt)

**Comment by dani8art** [comment]
Hi @Graeme-B 

I was unable to reproduce the issue, those are the steps I followed 

```console
$ openssl req -new -x509 -keyout ca.key -out ca.crt -days 3650 -passout pass:Testing1234 -subj "/CN=caroot/OU=CA/O=Kafka Test/L=Worthing/ST=West Sussex/C=UK"
$ docker run --rm -ti -v $(pwd):/workdir -w /workdir bitnami/java keytool -keystore truststore.jks -alias caroot -import -file ca.crt -storepass Testing1234 -noprompt
```

```console
$ docker run --rm -ti -v $(pwd):/workdir -w /workdir bitnami/java ./mkcerts.sh
```

After creating all the certificates, I started moving to get this directory structure

```
.
├── ca.crt
├── ca.key
├── ca.srl
├── certificates
│   ├── docker01
│   │   ├── kafka.keystore.jks
│   │   └── kafka.truststore.jks
│   ├── docker02
│   │   ├── kafka.keystore.jks
│   │   └── kafka.truststore.jks
│   ├── docker03
│   │   ├── kafka.keystore.jks
│   │   └── kafka.truststore.jks
│   └── docker4.jks
├── commands.sh
├── docker1.crt
├── docker1.signed
├── docker2.crt
├── docker2.signed
├── docker3.crt
├── docker3.signed
├── docker4.crt
├── docker4.signed
├── docker-compose.yml
├── mkcerts.sh
```

And use this `docker-compose.yaml`

```yaml
version: '3.7'
networks:
  kafka-net: null

services:
  zoo1:
    image: bitnami/zookeeper:3.4.12
    hostname: 'zoo1'
    networks:
      - kafka-net
    environment:
      ZOO_ENABLE_AUTH: 'no'
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      BITNAMI_DEBUG: 'true'

  kafka1:
    image: bitnami/kafka:2.5.0
    hostname: kafka1
    depends_on:
      - zoo1
    ports:
      - '9093:9093'
    volumes:
      - ./certificates/docker01:/bitnami/kafka/config/certs
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zoo1:2181'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL_HOST:SSL'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,SSL_HOST://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092,SSL_HOST://localhost:9093'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CERTIFICATE_PASSWORD: 'Testing1234'
      KAFKA_CFG_ENABLED_PROTOCOLS: 'TLSv1.2, TLSv1.1,TLSv1'
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: '/bitnami/kafka/config/certs/kafka.keystore.jks'
      KAFKA_CFG_SSL_KEY_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: '/bitnami/kafka/config/certs/kafka.truststore.jks'
      KAFKA_CFG_SSL_CLIENT_AUTH: 'required'
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_LOG_RETENTION_HOURS: 743
      BITNAMI_DEBUG: 'true'
    restart: always
    networks:
      - kafka-net

  kafka2:
    image: bitnami/kafka:2.5.0
    hostname: kafka2
    depends_on:
      - zoo1
    ports:
      - '9095:9095'
    volumes:
      - ./certificates/docker02:/bitnami/kafka/config/certs
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zoo1:2181'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL_HOST:SSL'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:29093,PLAINTEXT_HOST://:9094,SSL_HOST://:9095'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:29093,PLAINTEXT_HOST://localhost:9094,SSL_HOST://localhost:9095'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CERTIFICATE_PASSWORD: 'Testing1234'
      KAFKA_CFG_ENABLED_PROTOCOLS: 'TLSv1.2, TLSv1.1,TLSv1'
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: '/bitnami/kafka/config/certs/kafka.keystore.jks'
      KAFKA_CFG_SSL_KEY_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: '/bitnami/kafka/config/certs/kafka.truststore.jks'
      KAFKA_CFG_SSL_CLIENT_AUTH: 'required'
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_LOG_RETENTION_HOURS: 743
      BITNAMI_DEBUG: 'true'
    restart: always
    networks:
      - kafka-net

  kafka3:
    image: bitnami/kafka:2.5.0
    hostname: kafka3
    depends_on:
      - zoo1
    ports:
      - '9097:9097'
    volumes:
      - ./certificates/docker03:/bitnami/kafka/config/certs
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zoo1:2181'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL_HOST:SSL'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:29094,PLAINTEXT_HOST://:9096,SSL_HOST://:9097'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:29094,PLAINTEXT_HOST://localhost:9096,SSL_HOST://localhost:9097'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CERTIFICATE_PASSWORD: 'Testing1234'
      KAFKA_CFG_ENABLED_PROTOCOLS: 'TLSv1.2, TLSv1.1,TLSv1'
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: '/bitnami/kafka/config/certs/kafka.keystore.jks'
      KAFKA_CFG_SSL_KEY_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: 'Testing1234'
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: '/bitnami/kafka/config/certs/kafka.truststore.jks'
      KAFKA_CFG_SSL_CLIENT_AUTH: 'required'
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_LOG_RETENTION_HOURS: 743
      BITNAMI_DEBUG: 'true'
    restart: always
    networks:
      - kafka-net
```
