### ISSUE TITLE
java.io.IOException: Len error in Zookeeper when SASL_SSL is enabled

### ISSUE THREAD

**Issue by alfjjacob** [bitnami/bitnami-docker-kafka#129]
Hello,

I am setting up Kafka with SSL and Auth. docker-compose.yml is provided below. With this setup, Zookeeper is throwing the below error and Kafka dies after a few seconds. Please let me know if this should be reported in Zookeeper repo. 

```
2020-11-04 22:11:09,386 [myid:1] - WARN  [NIOWorkerThread-4:NIOServerCnxn@373] - Close of session 0x0
java.io.IOException: Len error 369296129
        at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:541)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:332)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

docker-compose.yml

```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - ${ZK_PORT}:${ZK_PORT}
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=kafka_password
    networks:
      - abc-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - ${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=abckafka
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=abckafka
      - KAFKA_CLIENT_USER=abc
      - KAFKA_CLIENT_PASSWORD=abc
      - KAFKA_CERTIFICATE_PASSWORD=abckafka
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SASL_SSL:SASL_SSL
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_SSL_CLIENT_AUTH=required
    networks:
      - abc-network
    volumes:
      - /home/centos/kafka-certs/certs:/bitnami/kafka/config/certs
```

**Comment by juan131** [comment]
Hi @alfjjacob 

It seems you configured Kafka correctly, but I don't see anywhere how you're configuring TLS on Zookeeper. 

- https://github.com/bitnami/bitnami-docker-kafka#kafka-zookeeper-client-configuration

I mean, you need to mount the keystore/truststore for Zookeeper in the Zookeeper container, and you need to set the environment variables below:

- ZOO_TLS_CLIENT_ENABLE
- ZOO_TLS_CLIENT_KEYSTORE_FILE
- ZOO_TLS_CLIENT_KEYSTORE_PASSWORD
- ZOO_TLS_CLIENT_TRUSTSTORE_FILE
- ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD

See https://github.com/bitnami/bitnami-docker-zookeeper#start-zookeeper-with-tls

---

Also, the mount point for the certificates in Kafka seems to be wrong:

```diff
    volumes:
-     - /home/centos/kafka-certs/certs:/bitnami/kafka/config/certs
+     - /home/centos/kafka-certs/certs:/bitnami/kafka/conf/certs
```

**Comment by alfjjacob** [comment]
@juan131 - Thanks for the prompt response. I was able to fix that particular issue after making the changes you suggested. However, I am getting a different error from Kafka now. 

`org.apache.kafka.common.KafkaException: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.`

Here is my latest docker-compose.yml

PS: I tried changing the mount points for certs to `bitnami/kafka/conf/certs ` but Kafka was complaining about missing certificates, so I reverted back that change

```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - ${ZK_PORT}:${ZK_PORT}
    environment:
            #- ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=kafka_password
      - ZOO_TLS_CLIENT_ENABLE=yes
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/kafka/conf/certs/zookeeper.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=abckafka
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/kafka/conf/certs/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=abckafka
        #- ZOO_HEAP_SIZE=512
    volumes:
      - /home/centos/kafka-certs/certs:/opt/bitnami/kafka/conf/certs
    networks:
      - abc-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - ${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:3181
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,CLIENT://kafka:9093,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://kafka:9093,EXTERNAL://abc.hsl.noam.lnrm.net:29093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL,CLIENT:SASL_SSL
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=abckafka
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=abckafka
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_CLIENT_USER=abc
      - KAFKA_CLIENT_PASSWORD=abc
      - KAFKA_CERTIFICATE_PASSWORD=abckafka
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_SSL_CLIENT_AUTH=required
    networks:
      - abc-network
    volumes:
      - /home/centos/kafka-certs/certs:/bitnami/kafka/config/certs
```

**Comment by juan131** [comment]
Hi @alfjjacob 

> However, I am getting a different error from Kafka now.
>
>org.apache.kafka.common.KafkaException: org.apache.kafka.common.config.ConfigException: Invalid value >javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created >with the provided settings can't connect to a server SSLEngine created with those settings.

That could be related to the FQDN validation. I mean, Kafka by default will validate the certificate matches the hostname of Zookeeper. Could you try setting the env vars below?

```
KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
```

> PS: I tried changing the mount points for certs to bitnami/kafka/conf/certs but Kafka was complaining about missing certificates, so I reverted back that change.

Ups! You're right! We need to fix the **README.md** since it's currently suggesting to use `/bitnami/kafka/conf/certs`.

**Comment by alfjjacob** [comment]
Hi @juan131 - Finally, I have a working setup. Thank You! 

I ended up including your recent recommendations and re-creating the certs by giving the FQDN of my server as the first name and last name as mentioned here https://github.com/bitnami/bitnami-docker-kafka#security. 

To create and consume messages, I followed these steps. https://docs.confluent.io/current/kafka/authentication_ssl.html#clients. I also had to export KAFKA_OPTS="-Djava.security.auth.login.config=kafka_jaas.conf". 

kafka_jass.conf was copied from the kafka brocker container. Is this the correct way of producing/consuming messages?

Here is my final docker-compose.yml
PS: I had to leave the value for this property as an empty string (double quotes did not work) 
KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=

```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - ${ZK_PORT}:${ZK_PORT}
    environment:
            #- ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=kafka_password
      - ZOO_TLS_CLIENT_ENABLE=yes
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/kafka/conf/certs/zookeeper.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=abckafka
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/kafka/conf/certs/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=abckafka
        #- ZOO_HEAP_SIZE=512
    volumes:
      - /home/centos/kafka-certs/certs2:/opt/bitnami/kafka/conf/certs
    networks:
      - abc-network

  kafka:
    hostname: abc.hsl.noam.lnrm.net
    image: 'bitnami/kafka:latest'
    ports:
      - ${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:3181
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,CLIENT://kafka:9093,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://kafka:9093,EXTERNAL://abc.xyz.net:29093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL,CLIENT:SASL_SSL
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=abckafka
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=abckafka
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CLIENT_USER=abc
      - KAFKA_CLIENT_PASSWORD=abc
      - KAFKA_CERTIFICATE_PASSWORD=abckafka
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_SSL_CLIENT_AUTH=required
    networks:
      - abc-network
    volumes:
      - /home/centos/kafka-certs/certs2:/bitnami/kafka/config/certs

```

**Comment by rafariossaa** [comment]
Hi @alfjjacob ,
  I am glad you were able to make it work. Thank you very much for the feedback provided.
  About the `kafka_jass.conf` file, I am not a kafka expert but I think you can use that.

**Comment by lconnell** [comment]
I'm receiving the exact same error. I also used the helper keystore script provided by Bitnami and I'm still encountering this issue.

```
version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
      - '3181:3181'
    volumes:
      - /tmp/bitnami/zookeeper:/bitnami/zookeeper
      - './ssl/keystore/kafka.keystore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks:ro'
      - './ssl/truststore/kafka.truststore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks:ro'
    environment:
      - ZOO_TLS_CLIENT_ENABLE=yes
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=password
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=password
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zookeeper
      - ZOO_SERVER_PASSWORDS=password
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=password
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - /tmp/bitnami/kafka:/bitnami/kafka
      - './ssl/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './ssl/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
      - './ssl/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro'
      - './ssl/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro'
      - './config/kafka_jaas.conf:/opt/bitnami/kafka/conf/kafka_jaas.conf:ro'
    environment:
      #- ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=password
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=password      
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=password
      - KAFKA_ZOOKEEPER_TLS_TYPE=JKS
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:3181
      - KAFKA_CFG_ADVERTISED_PORT=9092
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CERTIFICATE_PASSWORD=comcast
      - KAFKA_CFG_TLS_TYPE=JKS
      - KAFKA_SSL_CLIENT_AUTH=required
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    networks:
      - app-tier
    depends_on:
      - zookeeper
```

```
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
kafka_1      | 	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:98)
```
