### ISSUE TITLE
Jmx-exporter kafka issue not able to scrape the data with following configuration

### ISSUE THREAD

**Issue by avanichy25** [bitnami/bitnami-docker-kafka#130]
Hello,

I am using the following docker-compose configuration for jmx-exporter for kafka to get the jmx metrics but this is not working .Could you please help me over to fix the issue.

```yaml
kafka-exporter:
    image: docker.io/bitnami/kafka-exporter:1.2.0-debian-10-r220
    ports:
      - 9308:9308
    networks:
      - xxxxxx
    logging:
      options:
        max-size: 10m
    restart: always
    command: --kafka.server=kafka:9092

jmxexporter:
    image: docker.io/bitnami/jmx-exporter:0.13.0-debian-10-r73
    container_name: jmxexporter
    restart: unless-stopped
    ports:
      - 5556:5556
    networks:
      - xxxxx

version: '3'
services:
  kafka:
    image: kafka:2.5.0
    container_name: kafka
    ports:
    - 9092:9092
    - 9093:9093
    - 5555:5555
    links:
    - zookeeper
    volumes:
    - /data/kafka:/bitnami/kafka/data
    - ${KAFKA_SSL_DIR}/${KAFKA_SSL_KEYSTORE_FILENAME}:/bitnami/kafka/config/certs/xxxx
    - ${KAFKA_SSL_DIR}/${KAFKA_SSL_TRUSTSTORE_FILENAME}:/bitnami/kafka/config/certs/xxxxx
    - /var/log/kafka-logs:/opt/bitnami/kafka/logs
    environment:
    - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092,SSL://${KAFKA_ADVERTISED_HOST_NAME}:9093
    - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/xxxxx
    - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=${KAFKA_KEYSTORE_PASSWORD}
    - KAFKA_CERTIFICATE_PASSWORD=${KAFKA_KEYSTORE_PASSWORD}
    - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/xxxxx
    - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=${KAFKA_KEYSTORE_PASSWORD}
    - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    - KAFKA_SSL_CLIENT_AUTH=none
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    - KAFKA_CFG_LOG_RETENTION_BYTES=${KAFKA_LOG_RETENTION_BYTES}
    - KAFKA_CFG_LOG_SEGMENT_BYTES=250000000
    - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=30000
    - KAFKA_CFG_LOG_RETENTION_HOURS=168
    - KAFKA_CFG_LOG_CLEANER_ENABLE=true
    - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
    - JMX_PORT=5555
    networks:
      - xxxxxx
    logging:
      options:
        max-size: 10m
    depends_on:
      - zookeeper
    restart: always

   zookeeper:
    image: zookeeper:3.6.1-debian-10-r34
    volumes:
    - /data/zookeeper:/bitnami/zookeeper/data
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - xxxxx
    logging:
      options:
        max-size: 10m
    restart: always
```
Error 
`        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is:
        java.net.ConnectException: Connection refused (Connection refused)]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 17 more
Caused by: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is:
        java.net.ConnectException: Connection refused (Connection refused)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)`

**Comment by carrodher** [comment]
Are you facing the error in the exporter logs or in the main containers? I was trying to reproduce the issue using your _docker-compose.yaml_ but it seems it is pointing to local images or non-bitnami images, like `kafka:2.5.0`. In order to reproduce the same scenario, can you provide the _docker-compose.yaml_ you are using?

**Comment by avanichy25** [comment]
Hi , yes the images we are using are bitnami kafka 2.5 and bitnami zookeeper.

```kafka-exporter:
    image: docker.io/bitnami/kafka-exporter:1.2.0-debian-10-r220
    ports:
      - 9308:9308
    networks:
      - xxxxxx
    logging:
      options:
        max-size: 10m
    restart: always
    command: --kafka.server=kafka:9092

    jmxexporter:
    image: docker.io/bitnami/jmx-exporter:0.13.0-debian-10-r73
    container_name: jmxexporter
    restart: unless-stopped
    ports:
      - 5556:5556
    networks:
      - xxxxx

version: '3'
services:
  kafka:
    image: bitnami/kafka:2.5.0
    container_name: kafka
    ports:
    - 9092:9092
    - 9093:9093
    - 5555:5555
    links:
    - zookeeper
    volumes:
    - /data/kafka:/bitnami/kafka/data
    - ${KAFKA_SSL_DIR}/${KAFKA_SSL_KEYSTORE_FILENAME}:/bitnami/kafka/config/certs/xxxx
    - ${KAFKA_SSL_DIR}/${KAFKA_SSL_TRUSTSTORE_FILENAME}:/bitnami/kafka/config/certs/xxxxx
    - /var/log/kafka-logs:/opt/bitnami/kafka/logs
    environment:
    - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092,SSL://${KAFKA_ADVERTISED_HOST_NAME}:9093
    - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/xxxxx
    - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=${KAFKA_KEYSTORE_PASSWORD}
    - KAFKA_CERTIFICATE_PASSWORD=${KAFKA_KEYSTORE_PASSWORD}
    - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/xxxxx
    - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=${KAFKA_KEYSTORE_PASSWORD}
    - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    - KAFKA_SSL_CLIENT_AUTH=none
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    - KAFKA_CFG_LOG_RETENTION_BYTES=${KAFKA_LOG_RETENTION_BYTES}
    - KAFKA_CFG_LOG_SEGMENT_BYTES=250000000
    - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=30000
    - KAFKA_CFG_LOG_RETENTION_HOURS=168
    - KAFKA_CFG_LOG_CLEANER_ENABLE=true
    - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
    - JMX_PORT=5555
    networks:
      - xxxxxx
    logging:
      options:
        max-size: 10m
    depends_on:
      - zookeeper
    restart: always

   zookeeper:
    image: bitnami/zookeeper:3.6.1-debian-10-r34
    volumes:
    - /data/zookeeper:/bitnami/zookeeper/data
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - xxxxx
    logging:
      options:
        max-size: 10m
    restart: always
```

**Comment by carrodher** [comment]
I am sorry but I am not able to deploy the above _docker-compose.yaml_, it seems there are some format typos or it is incomplete. As it is a complex scenario I would like to reproduce it in the same conditions you're using. Can you provide the _docker-compose.yml_ you are using? Just to execute `docker-compose up`

**Comment by avanichy25** [comment]
Hi,
I have added the docker compose below with simple configuration:

```
version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
      - '9000:9000'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=9000
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9000
    depends_on:
      - zookeeper
  jmx-exporter:
    image: docker.io/bitnami/jmx-exporter:0-debian-10
    ports:
      - 5556:5556
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local ```

**Comment by carrodher** [comment]
Thanks for providing that docker-compose, I was able to deploy that scenario but I didn't find any issue, please see below the steps I did and the results:

- Deploy the above docker-compose.yaml without any modification. Using a clean environment (no existing images, volumes, containers, etc):
```console
$ docker-compose up -d
```
- Check that all the containers are up and running:
```console
$ docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
36b44a54229a        bitnami/kafka:2-debian-10          "/opt/bitnami/script…"   6 minutes ago       Up 6 minutes        0.0.0.0:9000->9000/tcp, 0.0.0.0:9092->9092/tcp         bitnami-components_kafka_1
cb2ae49b83d7        bitnami/jmx-exporter:0-debian-10   "java -jar jmx_prome…"   6 minutes ago       Up 6 minutes        0.0.0.0:5556->5556/tcp                                 bitnami-components_jmx-exporter_1
ad16af9549ce        bitnami/zookeeper:3-debian-10      "/opt/bitnami/script…"  6 minutes ago       Up 6 minutes        2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp   bitnami-components_zookeeper_1
```

- Check the container logs (just kafka and zookeeper as the exporter is not exposing logs in stdout):
```console
$ docker logs 36b44a54229a
...
[2020-11-11 14:46:01,966] INFO [SocketServer brokerId=1001] Started socket server acceptors and processors (kafka.network.SocketServer)
[2020-11-11 14:46:01,974] INFO Kafka version: 2.6.0 (org.apache.kafka.common.utils.AppInfoParser)
[2020-11-11 14:46:01,974] INFO Kafka commitId: 62abe01bee039651 (org.apache.kafka.common.utils.AppInfoParser)
[2020-11-11 14:46:01,974] INFO Kafka startTimeMs: 1605105961967 (org.apache.kafka.common.utils.AppInfoParser)
[2020-11-11 14:46:01,976] INFO [KafkaServer id=1001] started (kafka.server.KafkaServer)

$ docker logs ad16af9549ce
...
2020-11-11 14:45:58,903 [myid:1] - INFO  [main:FileTxnSnapLog@470] - Snapshotting: 0x0 to /bitnami/zookeeper/data/version-2/snapshot.0
2020-11-11 14:45:58,904 [myid:1] - INFO  [main:ZooKeeperServer@529] - Snapshot taken in 1 ms
2020-11-11 14:45:58,913 [myid:1] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@136] - PrepRequestProcessor (sid:0) started, reconfigEnabled=false
2020-11-11 14:45:58,914 [myid:1] - INFO  [main:RequestThrottler@74] - zookeeper.request_throttler.shutdownTimeout = 10000
2020-11-11 14:45:58,930 [myid:1] - INFO  [main:ContainerManager@83] - Using checkIntervalMs=60000 maxPerMinute=10000 maxNeverUsedIntervalMs=0
2020-11-11 14:45:58,931 [myid:1] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2020-11-11 14:46:00,638 [myid:1] - INFO  [SyncThread:0:FileTxnLog@284] - Creating new log file: log.1
```
I can't see any errors in the logs, nor the `Connection refused to host` you're facing. Can you check if there is a networking issue between the different containers?

- We can also access the containers and check the processes running into it, for example the exporter one:
```console
$ docker exec -ir cb2ae49b83d7 /bin/bash
I have no name!@cb2ae49b83d7:/opt/bitnami/jmx-exporter$ ps xufa
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001          41  0.1  0.0   3868  3240 pts/0    Ss   14:52   0:00 bash
1001          47  0.0  0.0   7640  2752 pts/0    R+   14:53   0:00  \_ ps xufa
1001           1  0.1  0.1 11648284 36172 ?      Ssl  14:45   0:00 java -jar jmx_prometheus_httpserver.jar 5556 example_configs/httpserver_sample_config.yml
```

Are you able to reproduce your issue by using this docker-compose.yaml?

**Comment by avanichy25** [comment]
@carrodher It works with the default example config which is pointing to the httpserver example but i want to change this to kafka config but somehow i am unable to do.

jmx-exporter
```
jmxexporter:
    image: docker.io/bitnami/jmx-exporter:0.13.0-debian-10-r73
    container_name: jmxexporter
    restart: unless-stopped
    volumes:
    - /root/jmx_exporter.yml:/opt/bitnami/jmx-exporter/jmx_exporter.yml
    ports:
      - 5556:5556
    command: java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm -jar jmx_prometheus_httpserver.jar 5556 /opt/bitnami/jmx-exporter/jmx_exporter.yml
```

Error:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "java"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at io.prometheus.jmx.WebServer.main(WebServer.java:21)

```

jmx-exporter.yml

```
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
ssl: false
whitelistObjectNames: ["kafka.controller:*","kafka.server:*","java.lang:*","kafka.network:*","kafka.log:*"]
rules:
  - pattern: kafka.controller<type=(ControllerChannelManager), name=(QueueSize), broker-id=(\d+)><>(Value)
    name: kafka_controller_$1_$2_$4
    labels:
      broker_id: "$3"
  - pattern: kafka.controller<type=(ControllerChannelManager), name=(TotalQueueSize)><>(Value)
    name: kafka_controller_$1_$2_$3
  - pattern: kafka.controller<type=(KafkaController), name=(.+)><>(Value)
    name: kafka_controller_$1_$2_$3
  - pattern: kafka.controller<type=(ControllerStats), name=(.+)><>(Count)
    name: kafka_controller_$1_$2_$3
  - pattern: kafka.server<type=(ReplicaFetcherManager), name=(.+), clientId=(.+)><>(Value)
    name: kafka_server_$1_$2_$4
    labels:
      client_id: "$3"
  - pattern : kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
    name: kafka_network_$1_$2_$4
    labels:
      network_processor: $3
  - pattern : kafka.network<type=(RequestMetrics), name=(RequestsPerSec), request=(.+)><>(Count)
    name: kafka_network_$1_$2_$4
    labels:
      request: $3
  - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>(Count|OneMinuteRate)
    name: kafka_server_$1_$2_$4
    labels:
      topic: $3
  - pattern: kafka.server<type=(DelayedOperationPurgatory), name=(.+), delayedOperation=(.+)><>(Value)
    name: kafka_server_$1_$2_$3_$4
  - pattern: kafka.server<type=(.+), name=(.+)><>(Count|Value|OneMinuteRate)
    name: kafka_server_$1_total_$2_$3
  - pattern: kafka.server<type=(.+)><>(queue-size)
    name: kafka_server_$1_$2
  - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
    name: java_lang_$1_$4_$3_$2
  - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
    name: java_lang_$1_$3_$2
  - pattern : java.lang<type=(.*)>
  - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
    name: kafka_log_$1_$2
    labels:
      topic: $3
```

Reference of jmx-exporter.yml from helm charts bitnami: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/jmx-configmap.yaml
