### ISSUE TITLE
Not Able Connect To kafka when use SASL_PLAINTEXT

### ISSUE THREAD

**Issue by mbasij1** [bitnami/bitnami-docker-kafka#133]
for my private  Kubernetes, I need to run the Kafka with SASL authentication to prevent not allowed access.
this is a sample docker-compose that I create for test that its works or not. but when I want to get the topics in 'kafka-tool' below error occured.
`Configured to use SASL_PLAINTEXT but broker 1001 does not support it`

```yaml
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - kafka_cfg_listeners=SASL_PLAINTEXT://:9092
      - kafka_cfg_advertised_listeners=SASL_PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_CLIENT_USER=user
      - KAFKA_CLIENT_PASSWORD=password
```
      
And for JAAS_config
`org.apache.kafka.common.security.plain.PlainLoginModule required     username="kafka"     password="kafka_password";`
