### ISSUE TITLE
Could not find a 'KafkaServer' or 'sasl_plaintext.KafkaServer' entry in the JAAS configuration

### ISSUE THREAD

**Issue by techiesspammer** [bitnami/bitnami-docker-kafka#145]
**Description**

I'm trying to run  kafka and zookeeper via docker, and it crashes because it couldn't find the `KafkaSever` or `'sasl_plaintext.KafkaServer` entry in the jaas configuration. See error message below.

```
kafka-bitnami                   | java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'sasl_plaintext.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /opt/bitnami/kafka/config/kafka_jaas.conf
kafka-bitnami                   | 	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
kafka-bitnami                   | 	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:96)
kafka-bitnami                   | 	at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:69)
kafka-bitnami                   | 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:131)
kafka-bitnami                   | 	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:97)
kafka-bitnami                   | 	at kafka.network.Processor.<init>(SocketServer.scala:790)
kafka-bitnami                   | 	at kafka.network.SocketServer.newProcessor(SocketServer.scala:415)
kafka-bitnami                   | 	at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:288)
kafka-bitnami                   | 	at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:287)
kafka-bitnami                   | 	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:254)
kafka-bitnami                   | 	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:251)
kafka-bitnami                   | 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka-bitnami                   | 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka-bitnami                   | 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka-bitnami                   | 	at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:251)
kafka-bitnami                   | 	at kafka.network.SocketServer.startup(SocketServer.scala:125)
kafka-bitnami                   | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:303)
kafka-bitnami                   | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
kafka-bitnami                   | 	at kafka.Kafka$.main(Kafka.scala:82)
kafka-bitnami                   | 	at kafka.Kafka.main(Kafka.scala)

```

I assumed that it had created a jaas configuration successfully because it printed out a message that it generated a JAAS authenticated file, and didn't throw any errors.. But it seems like it didn't? 

```
kafka-bitnami                   |  06:59:01.58
kafka-bitnami                   |  06:59:01.58 Welcome to the Bitnami kafka container
kafka-bitnami                   |  06:59:01.58 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka-bitnami                   |  06:59:01.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka-bitnami                   |  06:59:01.59
kafka-bitnami                   |  06:59:01.59 INFO  ==> ** Starting Kafka setup **
kafka-bitnami                   |  06:59:01.65 INFO  ==> Initializing Kafka...
kafka-bitnami                   |  06:59:01.66 INFO  ==> No injected configuration files found, creating default config files
kafka-bitnami                   |  06:59:01.72 INFO  ==> Generating JAAS authentication file
kafka-bitnami                   |  06:59:01.73 INFO  ==> Creating users in Zookeeper
kafka-bitnami                   |  06:59:04.46 INFO  ==> ** Kafka setup finished! **
kafka-bitnami                   |
kafka-bitnami                   |  06:59:04.48 INFO  ==> ** Starting Kafka **
```

**Steps to reproduce the issue:**

from my docker-compose.yml
```

  kafka-bitnami:
    image: bitnami/kafka:latest
    container_name: kafka-bitnami
    depends_on: ["zookeeper-bitnami"]
    ports: [ "9092:9092" ]
    networks: ["sandbox"]
    environment:
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ADVERTISED_PORT=9092
      - KAFKA_CLIENT_USERS=kafka
      - KAFKA_CLIENT_PASSWORDS=test
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=SASL_PLAINTEXT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=bitnami
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-bitnami:2181
 
  zookeeper-bitnami:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-bitnami
    hostname: zookeeper-bitnami
    ports: [ "2181:2181" ]
    networks: ["sandbox"]
    volumes:
      - 'zookeeper_data:/bitnami' 
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zookeeper
      - ZOO_SERVER_PASSWORDS=bitnami
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=test
```

**Other attempts I did to fix the issue**

When I tried mounting a `kafka_jaas.conf`  it crashes/exits without an explanation why it crashed. 

```
kafka-bitnami                   |  06:43:18.08
kafka-bitnami                   |  06:43:18.08 Welcome to the Bitnami kafka container
kafka-bitnami                   |  06:43:18.08 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka-bitnami                   |  06:43:18.09 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka-bitnami                   |  06:43:18.09
kafka-bitnami                   |  06:43:18.09 INFO  ==> ** Starting Kafka setup **
kafka-bitnami                   |  06:43:18.15 INFO  ==> Initializing Kafka...
kafka-bitnami                   |  06:43:18.16 INFO  ==> No injected configuration files found, creating default config files
kafka-bitnami                   |  06:43:18.23 INFO  ==> Custom JAAS authentication file detected. Skipping generation.
kafka-bitnami                   |  06:43:18.23 WARN  ==> The following environment variables will be ignored: KAFKA_CLIENT_USERS, KAFKA_CLIENT_PASSWORDS, KAFKA_INTER_BROKER_USER, KAFKA_INTER_BROKER_PASSWORD, KAFKA_ZOOKEEPER_USER and KAFKA_ZOOKEEPER_PASSWORD
kafka-bitnami                   |  06:43:18.23 INFO  ==> Creating users in Zookeeper
kafka-bitnami exited with code 1

```

the `kafka_jaas.conf` I'm trying to mount:
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
};

KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="kafka"
  password="test";
};
```

**OS version**: MacOs Catalina 10.15.6 (19G2021)
**Docker version:** 2.3.0.4
**Docker engine version:**  19.03.12
**Docker compose version:**  1.26.2
