### ISSUE TITLE
kafka_jaas.conf not configured

### ISSUE THREAD

**Issue by lconnell** [bitnami/bitnami-docker-kafka#147]
**Description**

Attempting to setup Kafka SASL_SSL following Bitnami docs

**Steps to reproduce the issue:**

```
version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - /tmp/bitnami/zookeeper:/bitnami/zookeeper
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=password
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - /tmp/bitnami/kafka:/bitnami/kafka
      - './ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ADVERTISED_PORT=9092
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=password
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_CFG_TLS_TYPE=JKS
    networks:
      - app-tier
    depends_on:
      - zookeeper
```

`docker-compose up -d`

**Describe the results you received:**

```
 20:46:20.23 INFO  ==> ** Starting Kafka **
[2021-03-10 20:46:29,435] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2021-03-10 20:46:31,886] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2021-03-10 20:46:32,154] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-03-10 20:46:32,158] INFO starting (kafka.server.KafkaServer)
[2021-03-10 20:46:32,159] INFO Connecting to zookeeper on zookeeper:2181 (kafka.server.KafkaServer)
[2021-03-10 20:46:32,186] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context [java.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf, zookeeper.sasl.client=default:true, zookeeper.sasl.clientconfig=default:Client]
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)
```

**Describe the results you expected:**

Kafka starts successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 93
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:2-99210772-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /app/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /app/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 16.22GB
 Data Space Total: 107.4GB
 Data Space Available: 30.03GB
 Metadata Space Used: 16.17MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.131GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 9.607GiB
Name: pieadm-wc-02
ID: KLGM:XZTQ:LBYH:2LSJ:I6L4:IT2S:EONQ:KRDF:PZCO:R76P:LTEF:MNFE
Docker Root Dir: /app/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @lconnell,

Could you check this issue https://github.com/bitnami/bitnami-docker-kafka/issues/98?

**Comment by lconnell** [comment]
I was able to mount a custom jaas config. Maybe the docs should be updated with this requirement?

**Comment by lconnell** [comment]
Now I'm running into this issue which seems related to issues [1279](https://github.com/bitnami/charts/issues/1279) and [129](https://github.com/bitnami/bitnami-docker-kafka/issues/129)

```
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:98)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:168)
```

**docker-compose.yml**
```
networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '3181:3181'
    volumes:
      - /tmp/bitnami/zookeeper:/bitnami/zookeeper
      - './ssl/server.keystore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks:ro'
      - './ssl/server.keystore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks:ro'
    environment:
      - ZOO_TLS_CLIENT_ENABLE=yes
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=password
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=password
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zookeeper
      - ZOO_SERVER_PASSWORDS=password
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=password
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - /tmp/bitnami/kafka:/bitnami/kafka
      - './ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
      - './ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro'
      - './ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro'
      - './config/kafka_jaas.conf:/opt/bitnami/kafka/conf/kafka_jaas.conf:ro'
    environment:
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=password
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=password
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=password
      - KAFKA_ZOOKEEPER_TLS_TYPE=JKS
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:3181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ADVERTISED_PORT=9092
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_CFG_TLS_TYPE=JKS
      - KAFKA_SSL_CLIENT_AUTH=required
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    networks:
      - app-tier
    depends_on:
      - zookeeper
```

**kafka_jaas.conf**
```
KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka"
    password="password";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka"
    password="password";
};

Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="zookeeper"
    password="password";
};
```
