### ISSUE TITLE
NoBrokersAvailable when accessing kafka with internal and external clients

### ISSUE THREAD

**Issue by diman82** [bitnami/bitnami-docker-kafka#151]
**Description**

I get kafka.errors.NoBrokersAvailable: NoBrokersAvailable trying to connect both from internal & external clients

**Steps to reproduce the issue:**

1. Follow the exact instructions at: https://github.com/bitnami/bitnami-docker-kafka#accessing-kafka-with-internal-and-external-clients

**Describe the results you received:**

NoBrokersAvailable

**Describe the results you expected:**

I except to be able to connect to kafka broker

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 24
  Running: 20
  Paused: 0
  Stopped: 4
 Images: 34
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 12.42GiB
 Name: docker-desktop
 ID: BCVO:REQ4:LABY:AMKU:Q737:KYD3:NYIX:N7FH:KCRT:27SV:3YUO:IGZU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 132
  Goroutines: 113
  System Time: 2021-03-24T16:54:43.6877215Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @diman82, unfortunately I've been unable to reproduce your issue using this exact docker-compose:

```
version: "2"

services:
  zookeeper:
    image: "docker.io/bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

Make sure that you properly updated the kafka node ports to `9093:9093` (and not `9092:9092` or `9093:9092`).

Also, I ran these commands to launch the producer/consumers **outside** of the containers (i.e. in the Docker host):

* **Producer:**

    ```
    $ ./kafka-console-producer.sh --broker-list 127.0.0.1:9093 --topic test
    ```

* **Consumer:**

    ```
    $ ./kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9093 --topic test --from-beginning
    ```

If you continue to find issues, please share more info on the specific steps you followed so we can help.

**Comment by diman82** [comment]
@marcosbc my kafka communication is purely internal (between containers).
Attached my docker-compose.yml

```
version: '3'

networks:
  app-tier:
    driver: bridge

services:
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    command: [ "python", "main.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_NAME=payments_log
    ports:
      - "80:80"
    networks:
      - app-tier
  risk-engine:
    build:
      context: ./risk-engine
      dockerfile: Dockerfile
    command: [ "python", "main.py" ]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=1
      - KAFKA_TOPIC_NAME=payments_log
    depends_on:
      - kafka
    networks:
      - app-tier
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=PAYMENTS
    networks:
      - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - app-tier
```

**Comment by marcosbc** [comment]
Hi @diman82, using the below docker-compose I could get it to work without issues using internal clients:

```yaml
version: '3'

services:
  kafka-client:
    image: 'bitnami/kafka:latest'
    command: sleep infinity
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
```

Then, to check the internal client, `docker-compose exec kafka-client bash` and run the following commands:

* Start producer (and send some messages):

    ```console
    $ kafka-console-producer.sh --broker-list kafka:9092 --topic test
    ```

* Start consumer (and receive the previously sent messages):

    ```console
    $ kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning
    ```

And in my previous post I shared that I could get external clients working as well.

Please let me know if I'm missing anything.
