### ISSUE TITLE
cp: cannot create regular file '/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks': Permission denied

### ISSUE THREAD

**Issue by DreamTexX** [bitnami/bitnami-docker-kafka#155]
Hey, so I've trying to mount the zookeeper keystore into the kafka container, like it wanted but when i mount it, it complains that it cannot create the file. My config is the following:

```yml
version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: kafka_zookeeper
    ports:
      - 3181:3181
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_TLS_CLIENT_ENABLE=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/tmp/zookeeper.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=***
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/tmp/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=***
    volumes:
      - ./zookeeper.keystore.jks:/tmp/zookeeper.keystore.jks:ro
      - ./zookeeper.truststore.jks:/tmp/zookeeper.truststore.jks:ro
  kafka:
    image: bitnami/kafka:2.8.0
    hostname: kafka.example.com
    container_name: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=***
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=***
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper.example.com:3181
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_CFG_LISTENERS=SASL_SSL://kafka.example.com:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://kafka.example.com:9092
      - KAFKA_CLIENT_USER=test
      - KAFKA_CLIENT_PASSWORD=test123
      - KAFKA_CERTIFICATE_PASSWORD=***
      - KAFKA_CFG_TLS_TYPE=JKS
    volumes:
      - kafka_data:/bitnami/kafka
      - ./kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      - ./zookeeper.keystore.jks:/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro
      - ./zookeeper.truststore.jks:/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro
volumes:
  kafka_data:
```
