### ISSUE TITLE
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record:

### ISSUE THREAD

**Issue by mbieren** [bitnami/bitnami-docker-kafka#156]
While trying to secure zookeeper with TLS it gets the following exception when a kafka broker tries to connect

`
2021-04-30 08:12:38,456 [myid:1] - WARN  [nioEventLoopGroup-7-7:NettyServerCnxnFactory$CnxnChannelHandler@293] - Exception caught
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record:
`

I am using the following docker-compose.yml 

```yml

version: '2'

services:

  zookeeper1:
    image: 'docker.io/bitnami/zookeeper:${BITNAMI_ZOOKEEPER_VERSION}'
    ports:
      - '2181'
      - '3181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zookeeper
      - ZOO_SERVER_PASSWORDS=myfinepassword
      - ZOO_CLIENT_USER=zookeeper
      - ZOO_CLIENT_PASSWORD=myfinepassword
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper1:2888:3888 #,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ZOO_TLS_CLIENT_ENABLE=true
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/bitnami/kafka/config/certs/kafka.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=myfinepassword
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/bitnami/kafka/config/certs/kafka.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=myfinepassword
    volumes:
      - 'zookeeper1_data:/bitnami'
      - ${keystore_mount}
      - ${truststore_mount}

  kafka:
    image: 'docker.io/bitnami/kafka:${BITNAMI_KAFKA_VERSION}'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:3181 #,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=myfinepassword
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=myfinepassword
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=myfinepassword
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://t-kafka01.baywa.de:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CLIENT_USERS=kafka
      - KAFKA_CLIENT_PASSWORDS=myfinepassword
      - KAFKA_SERVER_USERS=kafka
      - KAFKA_SERVER_PASSWORDS=myfinepassword
      - KAFKA_CERTIFICATE_PASSWORD=myfinepassword
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_TLS_TYPE=JKS
    volumes:
      - 'kafka_data:/bitnami'
      - ${keystore_mount}
      - ${truststore_mount}
      - ${zoo_keystore_mount}
      - ${zoo_truststore_mount}
    depends_on:
      - zookeeper1
    hostname: ${HOSTNAME}

volumes:
  kafka_data:
    driver: local
  zookeeper1_data:
    driver: local

```

.env is as follows

```
# Versions
BITNAMI_KAFKA_VERSION=2.8.0
BITNAMI_ZOOKEEPER_VERSION=3.7.0
# Defaults
ENVIRONMENT=dev
HOSTNAME=t-kafka01.baywa.de
keystore_mount=./ssl/keystore/kafka.keystore.jks.dev:/bitnami/kafka/config/certs/kafka.keystore.jks:ro
truststore_mount=./ssl/truststore/kafka.truststore.jks.dev:/bitnami/kafka/config/certs/kafka.truststore.jks:ro
zoo_keystore_mount=./ssl/keystore/kafka.keystore.jks.dev:/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro
zoo_truststore_mount=./ssl/truststore/kafka.truststore.jks.dev:/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro

```

Kafka is logging the following and stays there 
`
08:12:20.61 INFO  ==> Custom JAAS authentication file detected. Skipping generation.
 08:12:20.61 WARN  ==> The following environment variables will be ignored: KAFKA_CLIENT_USERS, KAFKA_CLIENT_PASSWORDS, KAFKA_INTER_BROKER_USER, KAFKA_INTER_BROKER_PASSWORD, KAFKA_ZOOKEEPER_USER and KAFKA_ZOOKEEPER_PASSWORD
 08:12:20.61 INFO  ==> Creating users in Zookeeper`

Eventually somebody has a working configuration with docker-compose and can help me out of this
