### ISSUE TITLE
[FEATURE REQUEST] Ability to run 2.8.0 without zookeeper (KIP-500)

### ISSUE THREAD

**Issue by rafaelsales** [bitnami/bitnami-docker-kafka#159]
Has anyone been able to run this image without zookeeper?

I've tried to pass the config specified here (https://www.confluent.io/blog/how-to-prepare-for-kip-500-kafka-zookeeper-removal-guide/), but no success

**Comment by carrodher** [comment]
Hi, at this moment I am not aware of a way to make it works standalone, both, our docker-compose and chart use ZooKeeper.
I will create an internal task to investigate this topic, but I can't provide an ETA for this task. I will keep the issue open just in case someone else in the community can add more info.

**Comment by OneCricketeer** [comment]
The correct documentation is here https://github.com/apache/kafka/tree/trunk/raft

**Comment by GuiBin2013** [comment]
Is there any plan to update the document about kafka2.8 ?
I saw the 2.8 image has updated in dockerhub.  Or I should try it by myself ? 

thank you~~

**Comment by carrodher** [comment]
> Is there any plan to update the document about kafka2.8 ?
> I saw the 2.8 image has updated in dockerhub. Or I should try it by myself ?
> 
> thank you~~

Hi, what document are you referring to?

**Comment by beatcracker** [comment]
I'm currently trying to make it work. Here is my compose file:

```yaml
version: '3'
services:
  kafka:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      # This configuration replaces `broker.id` for zk-based Kafka processes
      - KAFKA_CFG_NODE_ID=1

      # If this is null (absent) then we are in legacy mode.
      # Otherwise, we are in KIP-500 mode and this configuration determines what roles this process should play: broker, controller, or both.
      - KAFKA_CFG_PROCESS_ROLES=controller,broker

      # Needs to be set, otherwise startup fails with:
      # requirement failed: inter.broker.listener.name must be a listener name defined in advertised.listeners.
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL

      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
```

Currently it fails with:

```
No `meta.properties` found in /bitnami/kafka/data (have you run `kafka-storage.sh` to format the directory?)
```

This is because when running in KIP-500 mode, [the storage directories must be formatted using this command prior to starting up the brokers and controllers](https://cwiki.apache.org/confluence/display/KAFKA/KIP-631%3A+The+Quorum-based+Kafka+Controller#KIP631:TheQuorumbasedKafkaController-format).

So I guess the container entrypoint could be augmented with a check for  `KAFKA_CFG_NODE_ID` / `KAFKA_CFG_PROCESS_ROLES` variables and automatically format storage in case they're set.

**Comment by carrodher** [comment]
Thanks, I will add this information to the internal task I created to evaluate this proposal. In the meantime, as a workaround, you can try cloning this repository and building your own image (modifying the entrypoint or any other file).

**Comment by beatcracker** [comment]
@carrodher Thanks, I'll post an update if I manage to make it work.

**Comment by beatcracker** [comment]
Ok, for several reasons I'd prefer not to build custom image. Unfortunately the best I could do is this.

```yaml
version: '3.4'

# Common vars for multiple services
# stackoverflow.com/a/48651071/4424236
x-common-variables: &common-variables
  # Ensure same cluster id for all nodes
  CLUSTER_ID: lkorDA4qT6W1K_dk0LHvtg

  # If this is null (absent) then we are in legacy mode.
  # Otherwise, we are in KIP-500 mode and this configuration determines what roles this process should play: broker, controller, or both.
  # https://towardsdatascience.com/kafka-no-longer-requires-zookeeper-ebfbf3862104
  KAFKA_CFG_PROCESS_ROLES: 'controller,broker'

  # Bypass Zookeper user creation
  KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
  KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN'

  # Misc common settings
  ALLOW_PLAINTEXT_LISTENER: 'yes'
 
  KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL: 'SASL_PLAINTEXT'
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CLIENT:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT'
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'EXTERNAL'

services:
  kafka:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
      - '9093:9093'
    command:
      - 'sh'
      - '-c'
      - '/opt/bitnami/scripts/kafka/setup.sh && kafka-storage.sh format --config "$${KAFKA_CONF_FILE}" --cluster-id "$${CLUSTER_ID}" --ignore-formatted  && /opt/bitnami/scripts/kafka/run.sh'
    environment:
      <<: *common-variables

      # This configuration replaces `broker.id` for zk-based Kafka processes
      KAFKA_CFG_NODE_ID: '1'

      KAFKA_CFG_LISTENERS: 'CLIENT://:9092,EXTERNAL://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'CLIENT://kafka:9092,EXTERNAL://localhost:9093'
```

I successfully formats storage and tries to start Kafka, but fails with `java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.security.auth.SecurityProtocol.` Probably something is is wrong with my Kafka configuration, but I'm totally way out of my league here. Maybe somebody else could figure this out?

**Comment by OneCricketeer** [comment]
That error is related to the classpath of the server. 

And last I checked, KRaft doesn't work with any security features, plus you've said yes to the plaintext listener, so if suugest foregoing the SASL setup 

Plus, I think the bitnami run script still attempts kafka-server-start, which is not the same as the kraft mode startup script `test-kraft-server-start.sh`

**Comment by carrodher** [comment]
Thanks everyone for the information you provided, as it's mentioned by the Apache Kafka developers (see https://github.com/apache/kafka/blob/trunk/config/kraft/README.md#warning), at this moment is a beta feature not recommended for production. We have an internal task to investigate this new feature and how we can, in the future, incorporate it to the container image. Being said that, we don't expect to apply changes into the current image until this feature reaches a mature status in the upstream project; in the same way, the Bitnami image is open source and the code is available in this repository so you should be able to play with it and build your own image in the meantime.

**Comment by ntx-ben** [comment]
I've managed to make it work in Kubernetes without modifying the docker image. I've used an `initContainer` to first format the storage. I've also injected the `server.properties` file as provided in the [official KRaft docs](https://github.com/apache/kafka/blob/trunk/config/kraft/server.properties). As mentioned this is still beta so not security features are working at the moment as far as I can tell.

**Comment by vuldin** [comment]
> I've managed to make it work in Kubernetes without modifying the docker image. I've used an `initContainer` to first format the storage. I've also injected the `server.properties` file as provided in the [official KRaft docs](https://github.com/apache/kafka/blob/trunk/config/kraft/server.properties). As mentioned this is still beta so not security features are working at the moment as far as I can tell.

That's great that you were able to get KRaft mode working in this helm chart @ntx-ben . Would you be able to post the steps to replicate this process?

**Comment by ntx-ben** [comment]
I'm not using helm but kustomize with in-house manifest definitions. Here's the various simplified manifests I'm using. This is not production ready, obviously, but it's enough to play around (I use `kind` and the [local-path-provisioner](https://github.com/rancher/local-path-provisioner) storage provider).

kafka-configmap.yaml
```
apiVersion: v1
data:
  server.properties: |-
    # copy & paste the contents from https://github.com/apache/kafka/blob/trunk/config/kraft/server.properties
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: kafka
  name: kafka
  namespace: kafka
```

kafka-statefulset.yaml
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  serviceName: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      containers:
      - command:
        - sh
        - -c
        - cp /opt/bitnami/kafka/config/kraft/server.properties /opt/bitnami/kafka/config/server.properties
          && /opt/bitnami/scripts/kafka/run.sh
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: CLUSTER_ID
          value: ZbxI0SJZRiKLJNHusxNHQQ
        image: bitnami/kafka:2.8.0-debian-10-r31
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
          name: client
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 50m
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 1001
        volumeMounts:
        - mountPath: /opt/bitnami/kafka/config/kraft/server.properties
          name: kafka-config
          subPath: server.properties
        - mountPath: /tmp/kraft-combined-logs
          name: kafka-data
      initContainers:
      - command:
        - sh
        - -c
        - kafka-storage.sh format --config "/opt/bitnami/kafka/config/server.properties"
          --cluster-id "${CLUSTER_ID}" --ignore-formatted
        env:
        - name: CLUSTER_ID
          value: ZbxI0SJZRiKLJNHusxNHQQ
        image: bitnami/kafka:2.8.0-debian-10-r31
        name: format-storage
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /opt/bitnami/kafka/config/server.properties
          name: kafka-config
          subPath: server.properties
        - mountPath: /tmp/kraft-combined-logs
          name: kafka-data
      securityContext:
        fsGroup: 1000
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka
        name: kafka-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/name: kafka
      name: kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: local-path
```

kafka-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka
  name: kafka
  namespace: kafka
spec:
  ports:
  - name: client
    port: 9092
    protocol: TCP
    targetPort: client
  selector:
    app.kubernetes.io/name: kafka
  type: ClusterIP
```

**Comment by carrodher** [comment]
Thanks for sharing this info with the community!

**Comment by juan131** [comment]
Hi @spham 

The Kraft mode isn't supported out-of-the-box in this image at this very moment. Therefore, you need to overwrite the Bitnami automations and use your custom configuration for Kafka to use this mode, see:

- https://github.com/bitnami/bitnami-docker-kafka#full-configuration

**Comment by carrodher** [comment]
Unfortunately, since we are a small team with a limited bandwidth we are focusing on adding stable and production-ready features. Although this is a good-to-have feature, it is not mature enough to be considered production-ready.
We will evaluate this addition after some time, but at this moment there are no plans to work on it in the short/mid term.
Being said that, PRs are welcome and we will happy to review any contribution.

**Comment by dyaacov** [comment]
https://hub.docker.com/r/moeenz/docker-kafka-kraft

**Comment by nightswimmings** [comment]
Unfortunately https://hub.docker.com/r/moeenz/docker-kafka-kraft does not seem maintained anymore and not supporting 
 Kafka 3.x
 
 
 I think this is a much more relevant feature than it is apparent, it helps a lot to test/play with kafka for beginners with a minimum preconfigured setup

**Comment by whithajess** [comment]
Working docker-compose file for those who are interested:

```
version: '3'
services:
  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka
    command:
      - 'sh'
      - '-c'
      - '/opt/bitnami/scripts/kafka/setup.sh && kafka-storage.sh format --config "$${KAFKA_CONF_FILE}" --cluster-id "lkorDA4qT6W1K_dk0LHvtg" --ignore-formatted  && /opt/bitnami/scripts/kafka/run.sh' # Kraft specific initialise
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Start Kraft Setup (Kafka as Controller - no Zookeeper)
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/logs
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # End Kraft Specific Setup
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    ports:
      - 0.0.0.0:9092:9092
```

**Comment by whithajess** [comment]
@carrodher I can put this into the `README` as an example if you want me to push up a PR

**Comment by carrodher** [comment]
Thanks, sure, feel free to create a PR adding a description and the code snippet, the team will be happy to review it and provide feedback

**Comment by whithajess** [comment]
@carrodher Done hopefully pretty straightforward, happy to make changes as required!

**Comment by sherbang** [comment]
Here's a working values.yaml for use with the bitnami helm chart.  Based on @whithajess's docker-compose recipe.

Usage:
```sh
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install -f values.yaml my-release bitnami/kafka
```
values.yaml:
```yaml
listeners:
  - PLAINTEXT://:9092
  - CONTROLLER://:9093
advertisedListeners:
  - "PLAINTEXT://$(MY_POD_NAME).kafka-headless.kafka.svc.cluster.local:9092"
listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
allowPlaintextListener: true
interBrokerListenerName: PLAINTEXT
command:
  - /opt/bitnami/scripts/kafka/entrypoint.sh
  - "sh"
  - "-c"
  - |
    set -ex
    /opt/bitnami/scripts/kafka/setup.sh
    export KAFKA_CFG_BROKER_ID="$(kafka-storage.sh random-uuid)"
    kafka-storage.sh format --config "${KAFKA_CONF_FILE}" --cluster-id "${KAFKA_CFG_BROKER_ID}" --ignore-formatted
    /opt/bitnami/scripts/kafka/run.sh
extraEnvVars:
  # Kraft Setup (Kafka as Controller - no Zookeeper)
  - name: KAFKA_CFG_NODE_ID
    value: "1"
  - name: KAFKA_CFG_BROKER_ID
    value: "1"
  - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
    value: 1@127.0.0.1:9093
  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
    value: CONTROLLER
  - name: KAFKA_CFG_PROCESS_ROLES
    value: broker,controller
zookeeper:
  enabled: false
```
