### ISSUE TITLE
SASL_PLAINTEXT authentication configuration issue

### ISSUE THREAD

**Issue by dilanSachi** [bitnami/bitnami-docker-kafka#163]
**Description**

Having trouble when creating `SASL_PLAINTEXT` authentication configuration in the docker environment. Im trying to have two ports to communicate both with `PLAINTEXT` and also `SASL_PLAINTEXT`.

**Steps to reproduce the issue:**

1. This is my dockerfile

```
version: '2'

services:
    zookeeper-consumer:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
            - ALLOW_PLAINTEXT_LISTENER=yes
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
            - '9093:9093'
        environment:
            - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-consumer:2181
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
            - KAFKA_CFG_SASL_ENABLED_MECHANISM=PLAIN
            - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
            - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
        volumes:
            - ./kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
        depends_on:
            - zookeeper-consumer
```

2. This is the `kafka_server_jaas.conf` file.
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="password"
  user_admin="password";
};
```
**Describe the results you received:**

```
kafka_1               | [2021-05-25 11:00:50,916] WARN SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/opt/bitnami/kafka/config/kafka_jaas.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
kafka_1               | [2021-05-25 11:00:50,918] INFO Opening socket connection to server zookeeper-consumer/172.21.0.2:2181 (org.apache.zookeeper.ClientCnxn)
kafka_1               | [2021-05-25 11:00:50,919] ERROR [ZooKeeperClient Kafka server] Auth failed. (kafka.zookeeper.ZooKeeperClient)
```

**Describe the results you expected:**

Both the `Zookeeper` and `Broker` seems to be up and running. But I see the above error and also cannot connect to a broker via `PLAINTEXT:9092` or `SASL_PLAINTEXT:9092`

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 4
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-53-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.43GiB
 Name: dilans
 ID: 6GUK:GAW2:BJRS:ONR3:2YOK:4PIT:TFY6:LX6A:OHD6:7XDE:QGD3:CSCF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on Ubunutu 20.04

**Comment by rafariossaa** [comment]
Hi,
  I would suggest you to first try to deploy without providing the config file. The initialization logic will create the appropriate config file. I would say by the error, that something like what is [generated here]([https://github.com/bitnami/bitnami-docker-kafka/blob/636334c141bbb8a2b7aba1742114b04f9ed00099/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L440)) is missing.
  Could you take a look to it ?.

**Comment by dilanSachi** [comment]
Hi. Thanks for the response. But I first tried it out without the config file also. That also results in an error

**Comment by rafariossaa** [comment]
Hi,
  Sorry, I missed a link in my previous comment.
  The config file should have the client sections that is [generated here](https://github.com/bitnami/bitnami-docker-kafka/blob/636334c141bbb8a2b7aba1742114b04f9ed00099/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L440).
  Could you check if you have it ?.

**Comment by dilanSachi** [comment]
Hi,
Thanks for the help. I tried it out and ended with the following config file.

```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  serviceName="yourServiceName"
  username="admin"
  password="password"
  user_admin="password";
};

Server {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="password"
  user_admin="password";
};

KafkaClient {
org.apache.kafka.common.security.plain.PlainLoginModule required
  serviceName="yourServiceName"
  username="admin"
  password="password";
};
```

And I had to change the `docker` file to,

```
version: '2'

services:
    zookeeper-consumer:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ZOO_ENABLE_AUTH=yes
            - ZOO_SERVER_USERS=admin
            - ZOO_SERVER_PASSWORDS=password
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
            - '9093:9093'
        environment:
            - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-consumer:2181
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
            - KAFKA_CFG_SASL_ENABLED_MECHANISM=PLAIN
            - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
            - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
            - KAFKA_CLIENT_USERS=admin
            - KAFKA_CLIENT_PASSWORDS=password
        volumes:
            - ./kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
        depends_on:
            - zookeeper-consumer
```

Somehow, I cannot use `SASL_PLAINTEXT` authentication only between brokers and clients. I have to configure it for `zookeeper -> broker` also. I was able to successfully start the `Kafka` cluster with above configs, but my client does not receive any response from the `broker`. So I tried out `Kafka` docker image from [Confluent](https://github.com/confluentinc/kafka-images) and I was able to successfully setup my cluster.

I'm closing this issue since I was able to find a solution. Thanks a lot for the quick help.
