### ISSUE TITLE
KAFKA_CFG_LISTENER_* environment variables not honored.

### ISSUE THREAD

**Issue by raffaelespazzoli** [bitnami/bitnami-docker-kafka#169]
I'm configuring kafka with some dynamic (calculated at pod start) environment variables and the rest of the config from the kafka property file.
Not sure if this more was supposed to be supported but it looks like it does not work and neither of the `KAFKA_CFG_LISTENER_*` seems to be honored: `KAFKA_CFG_LISTENERS`, `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP`,  `KAFKA_CFG_ADVERTISED_LISTENERS`

**Additional information you deem important (e.g. issue happens only occasionally):**

if the kafka property file supported parametric properties based on env variables, that could be another way of solving the issue.

**Version**

kafka image 2.7.0,  containers are deployed as pods in OCP 4.7

**Comment by marcosbc** [comment]
Hi @raffaelespazzoli, any environment variables starting with `KAFKA_CFG_` will be appended automatically to the `server.properties` configuration file for Kafka during initialization.

Could it be you are checking `producer.properties` or `consumer.properties` instead? Note that those files are not populated automatically via such environment variables.

**Comment by raffaelespazzoli** [comment]
I see, I pass the config as a configmap in a kubernetes pod, so whatever the script tries to append will be reset by kubernetes. Are you designing these images to be run in kubernetes?

**Comment by raffaelespazzoli** [comment]
#168 might be related. I'm using the tag 2.8.0.

**Comment by marcosbc** [comment]
Hi, we are indeed allowing Kafka to run on Kubernetes with the [Kafka chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka). I'm still a bit confused by this issue, though.

> if the kafka property file supported parametric properties based on env variables, that could be another way of solving the issue.

Note that what you are saying here is already happening with the current logic. For instance, if you set `KAFKA_CFG_HELLO_WORLD=hello` then the following entry will appear in `server.properties`:

```
hello.world=hello
```

However it will not replace `consumer.properties` nor `producer.properties`, and that is expected.

If you are still finding issues, could you describe it with more details? I.e.:

* How you are deploying the solution, incl. commands and anything like that
* What [wrong] result you are obtaining
* What should be the expected result

**Comment by neexee** [comment]
Hi!

From my observations, the [Kafka chart](https://github.com/bitnami/charts/tree/master/bitnami/kafka) uses `KAFKA_CFG_ADVERTISED_LISTENERS` everywhere. But when I deploy Kafka using the chart, brokers return default set of listeners.

My values.yml looks roughly like this:
```
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3

numPartitions: 3
replicaCount: 3

persistence:
  storageClass: longhorn-1repl
  size: 50G

advertisedListeners:
  - INTERNAL://${MY_POD_NAME}.kafka-headless.dev.svc.cluster.local:9093
  - CLIENT://${MY_POD_NAME}.kafka-headless.dev.svc.cluster.local:9092
  - EXTERNAL://${MY_POD_NAME}.my.domain:9094

externalAccess:
  enabled: true
  service:
    type: LoadBalancer
```

For deployment verification I'm running a command like this
```
$ kafkacat -b kafka-2.my.domain:9094 -L | head
```
And get a response like this:
```
Metadata for all topics (from broker 2: kafka-2.my.domain:9094/2):
 3 brokers:
  broker 0 at LoadBalancerIP1:9094
  broker 2 at LoadBalancerIP2:9094 (controller)
  broker 1 at LoadBalancerIP3:9094
```
But that's not what I want, I wanted Kafka to advertise `EXTERNAL://${MY_POD_NAME}.my.domain:9094`, not IPs given by LoadBalancer.

After some digging I found that replacing `KAFKA_CFG_ADVERTISED_LISTENERS` to `KAFKA_ADVERTISED_LISTENERS` in chart works as expected.

```
$ kafkacat -b kafka-2.my.domain:9094 -L | head

Metadata for all topics (from broker 2: kafka-2.my.domain:9094/2):
 3 brokers:
  broker 0 at kafka-0.my.domain:9094
  broker 2 at kafka-1.my.domain:9094 (controller)
  broker 1 at kafka-2.my.domain:9094
```

The change is here https://github.com/neexee/charts/commit/ab0271e8d89ed8bc97301724feca23770fb9d2ad

Can you please take a look at this? I don't know where it should be fixed, on bitnami-docker-kafka side or in Kafka chart.
