### ISSUE TITLE
docker container works with debug program, fail when put the program in container

### ISSUE THREAD

**Issue by Kowiste** [bitnami/bitnami-docker-kafka#173]
I have this docker compose :
```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
    networks:
      - web 
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    restart:  always
    depends_on:
      - zookeeper
    networks:
      - web  
networks:
  web:
    external: true
```

I have a program  debugging in vscode an everything works, the problem is when I make a container with this program. I have  this error every time the program try to write on kafka .
` kafka write errors (1/1)`
```
version: "3"
services:
  gateway:
    build: .
    container_name: service-gateway
    restart: unless-stopped
    environment: 
      - REDIS_ADDR=redisDB
      - KAFKA_ADDR=broker
    networks:
      - web  
networks:
  web:
    external: true
```

When I debug the program the only change is  the KAFKA_ADDR variable is set to localhost.
I suppose that I have some error in  the network configuration but don't know what can  be.
