### ISSUE TITLE
Problems with SSL/PEM

### ISSUE THREAD

**Issue by astenman** [bitnami/bitnami-docker-kafka#185]
Hello! Thank you for your good work! 

I am trying to deploy with docker-compose using SSL/PEM for both zookeeper and the brokers.

I have to mount the PEM certs as

```
      - kafka_0_data:/data/kafka/kafka
      - './kafka.keystore.pem:/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      - './kafka.keystore.key:/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      - './kafka.truststore.pem:/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
      - './zookeeper.keystore.pem:/bitnami/kafka/config/certs/zookeeper.keystore.pem:ro'
      - './zookeeper.keystore.key:/bitnami/kafka/config/certs/zookeeper.keystore.key:ro'
      - './zookeeper.truststore.pem:/bitnami/kafka/config/certs/zookeeper.truststore.pem:ro'
```

i.e., without a leading `/opt/bitnami ...` in order to get the certs detected.

At least the log says 

```
kafka-0_1    | kafka 15:23:35.59 INFO  ==> Copying truststore /bitnami/kafka/config/certs/kafka.truststore.pem to /opt/bitnami/kafka/config/certs
kafka-0_1    | kafka 15:23:35.59 INFO  ==> Copying truststore /bitnami/kafka/config/certs/zookeeper.truststore.pem to /opt/bitnami/kafka/config/certs
```

But later on, the brokers fail with the following messages

```
Caused by: java.lang.IllegalArgumentException: Unable to auto-detect store file type from file name: /opt/bitnami/kafka/config/certs/
```

Is this expected? Maybe I have misunderstood something?

**Comment by marcosbc** [comment]
Hi @astenman, that error seems to indicate a misconfiguration in Kafka. Could you check the values for `ssl.truststore.location` in the Kafka configuration files (`server.properties` and `consumer.properties`/`producer.properties`)?

In addition, could you share the full list of environment variables used to deploy Kafka?

**Comment by astenman** [comment]
Thanks!

I currently have a lot of problems regarding folder access rights. As I have understood it, the containers run as user 1001.

I have updated the folder rights accordingly

```
root@kafka01:/data/kafka# id niralocal
uid=1001(niralocal) gid=1001(niralocal) groups=1001(niralocal),27(sudo)
root@kafka01:/data/kafka# ls -lsa
total 128
 4 drwxrwxr-x 6 niralocal root  4096 Aug 18 11:06 .
 4 drwxr-xr-x 3 root      root  4096 Aug 17 10:51 ..
 4 -rw-r--r-- 1 niralocal root  3286 Aug 18 11:06 docker-compose.yml
 4 -rw-r--r-- 1 niralocal root    90 Aug 17 21:48 .env
 4 drwxr-xr-x 8 niralocal root  4096 Aug 18 11:06 .git
 4 -rw-r--r-- 1 niralocal root   203 Aug 18 10:29 .gitignore
 4 drwxr-xr-x 2 root      root  4096 Aug 18 11:06 kafka_0_data
 4 drwxr-xr-x 2 root      root  4096 Aug 18 11:06 kafka_1_data
 8 -rwxr-xr-x 1 niralocal root  7382 Aug 17 16:39 kafka-generate-ssl.sh
 4 -rw-rw-r-- 1 niralocal root  1777 Aug 18 09:46 kafka.keystore.key
 4 -rw-rw-r-- 1 niralocal root  3920 Aug 18 10:05 kafka.keystore.pem
 4 -rw-rw-r-- 1 niralocal root  1322 Aug 17 20:20 kafka.truststore.pem
 4 -rw-r--r-- 1 niralocal root   743 Aug 17 10:51 README.md
56 -rw-r--r-- 1 niralocal root 54656 Aug 17 10:51 values.yaml
 4 drwxr-xr-x 2 root      root  4096 Aug 18 11:06 zookeeper_data
 4 -rw-rw-r-- 1 niralocal root  1777 Aug 18 09:47 zookeeper.keystore.key
 4 -rw-rw-r-- 1 niralocal root  3920 Aug 18 10:06 zookeeper.keystore.pem
 4 -rw-rw-r-- 1 niralocal root  1322 Aug 17 20:22 zookeeper.truststore.pem
root@kafka01:/data/kafka#
```
But when I run `docker-compose up` as root the data folders are not created as expected (which is understandable, since they are created with the wrong rights). 

My config is included below. We would like to run kafka with SSL and PEM certs and persistent data. Maybe I am stupid, but I cannot figure out how to configure that.

```
version: "2"

services:
  zookeeper:
    image: dockerhub.niradynamics.se/bitnami/zookeeper:3.7
    hostname: kafka01.niradynamics.se
    ports:
      - "2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=srvkafka
      - ZOO_SERVER_PASSWORDS=$KAFKA_ZOOKEEPER_PASSWORD
    volumes:
      - "./zookeeper_data:/bitnami/zookeeper:rw"
  kafka-0:
    image: dockerhub.niradynamics.se/bitnami/kafka:2
    hostname: kafka01.niradynamics.se
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:19092,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,CLIENT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_PROTOCOL=SSL
      - KAFKA_ZOOKEEPER_TLS_TYPE=PEM
      - KAFKA_ZOOKEEPER_USER=srvkafka
      - KAFKA_ZOOKEEPER_PASSWORD=$KAFKA_ZOOKEEPER_PASSWORD
      - KAFKA_CLIENT_USERS=kafka-client
      - KAFKA_CLIENT_PASSWORDS=$KAFKA_CLIENT_PASSWORDS
      - KAFKA_TLS_TYPE=PEM
    volumes:
      - "./kafka_0_data:/bitnami/kafka:rw"
      - "./kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem"
      - "./kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key"
      - "./kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem"
      - "./zookeeper.keystore.pem:/opt/bitnami/kafka/config/certs/zookeeper.keystore.pem"
      - "./zookeeper.keystore.key:/opt/bitnami/kafka/config/certs/zookeeper.keystore.key"
      - "./zookeeper.truststore.pem:/opt/bitnami/kafka/config/certs/zookeeper.truststore.pem"
    depends_on:
      - zookeeper
  kafka-1:
    image: dockerhub.niradynamics.se/bitnami/kafka:2
    hostname: kafka01.niradynamics.se
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:19093,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:19093,CLIENT://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_PROTOCOL=SSL
      - KAFKA_ZOOKEEPER_TLS_TYPE=PEM
      - KAFKA_ZOOKEEPER_USER=srvkafka
      - KAFKA_ZOOKEEPER_PASSWORD=$KAFKA_ZOOKEEPER_PASSWORD
      - KAFKA_CLIENT_USERS=kafka-client
      - KAFKA_CLIENT_PASSWORDS=$KAFKA_CLIENT_PASSWORDS
      - KAFKA_TLS_TYPE=PEM
    volumes:
      - "./kafka_1_data:/bitnami/kafka:rw"
      - "./kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem"
      - "./kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key"
      - "./kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem"
      - "./zookeeper.keystore.pem:/opt/bitnami/kafka/config/certs/zookeeper.keystore.pem"
      - "./zookeeper.keystore.key:/opt/bitnami/kafka/config/certs/zookeeper.keystore.key"
      - "./zookeeper.truststore.pem:/opt/bitnami/kafka/config/certs/zookeeper.truststore.pem"
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
```
