### ISSUE TITLE
Kafka exiting with code 1 if not mapping volume

### ISSUE THREAD

**Issue by chadgrant** [bitnami/bitnami-docker-kafka#19]
Been debugging this for awhile, I'm using self signed certs. Kafka quits the first time I connect unless I map a volume it is stable. Using golang to connect and need SSL here is the config:

  ```
zookeeper:
    container_name: lpg_zookeeper
    image: bitnami/zookeeper:3.4.12
    ports:
      - "2181:2181"
    environment: 
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    container_name: lpg_kafka
    image: bitnami/kafka:1.1.0
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
        - zookeeper
    environment:
      KAFKA_LISTENERS: SASL_SSL://kafka:9093,SSL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka:9093,SSL://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CERTIFICATE_PASSWORD: password
    volumes:
      - './certs/kafka/keystore/kafka.keystore.jks:/opt/bitnami/kafka/conf/certs/kafka.keystore.jks:ro'
      - './certs/kafka/truststore/kafka.truststore.jks:/opt/bitnami/kafka/conf/certs/kafka.truststore.jks:ro'
      - ~/.docker-kafka:/bitnami/kafka
```
