### ISSUE TITLE
How to use SASL_PLAINTEXT authentication profile

### ISSUE THREAD

**Issue by ktpktr0** [bitnami/bitnami-docker-kafka#192]
I noticed that the example uses clear text account and password, so I want to use the file method to configure, but I failed.

docker-compose:
```
version: '3.0'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6'
    container_name: zookeeper
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      #- ZOO_SERVER_USERS=kafka
      #- ZOO_SERVER_PASSWORDS=tmpaaaa
      - KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/zookeeper/conf/zk_server_jaas.conf"
    volumes:
      - ./zookeeper/conf/zk_server_jaas.conf:/opt/bitnami/zookeeper/conf/zk_server_jaas.conf
      - ./zookeeper/data:/bitnami/zookeeper

  kafka:
    image: 'bitnami/kafka:2.8.1'
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://localhost:9093
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      #- KAFKA_ZOOKEEPER_USER=kafka
      #- KAFKA_ZOOKEEPER_PASSWORD=tmpaaaa
      - KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_server_jaas.conf"
      - KAFKA_CFG_MAX_REQUEST_SIZE=1048576000
    volumes:
      - ./kafka/data:/bitnami/kafka
      - ./kafka/config/kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_server_jaas.conf
      #- /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
```
kafka log:

```
kafka 19:46:40.85 
kafka 19:46:40.85 Welcome to the Bitnami kafka container
kafka 19:46:40.85 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 19:46:40.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 19:46:40.86 
kafka 19:46:40.86 INFO  ==> ** Starting Kafka setup **
kafka 19:46:41.00 ERROR ==> In order to configure SASL authentication for Kafka, you must provide the SASL credentials. Set the environment variables KAFKA_ZOOKEEPER_USER and KAFKA_ZOOKEEPER_PASSWORD, to configure the credentials for SASL authentication with Zookeeper.
```
The log prompts that the account password must be configured in clear text, I want to know how to use the file method to authenticate SASL
