### ISSUE TITLE
Cannot find Server.Properties

### ISSUE THREAD

**Issue by Tenseiga** [bitnami/bitnami-docker-kafka#20]

**Comment by javsalgar** [comment]
Hi,

I just launched this docker-compose 

```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```
The server.properties file is in `/opt/bitnami/kafka/conf/server.properties`
