### ISSUE TITLE
Kafka broker not able to create SSLContext to connect with ZK. 

### ISSUE THREAD

**Issue by spaceVStab** [bitnami/bitnami-docker-kafka#202]
**Description**
I am trying to setup a SSL enabled Kafka stack with Bitnami version of kafka. I have created the certificates required and pass them through environment variables. Also find the docker-compose.yml being used:

```
---
version: '3.5'
services:

    ####
    #
    # This file overrides values from environment/plaintext/docker-compose.yml
    #
    ####

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ../../environment/2way-ssl/security:/bitnami/kafka/config/certs

  broker:
    hostname: kafka
    ports:
      - 9092:9092
    image: bitnami/kafka:2.8.1-debian-10-r51
    environment:
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SSL://:9092
      - KAFKA_LISTENERS=SSL://:9092
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_SSL_KEYSTORE_FILENAME=kafka.keystore.jks
      - KAFKA_SSL_TRUSTSTORE_FILENAME=kafka.truststore.jks
      - KAFKA_CFG_SSL_KEYSTORE_FILENAME=kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_FILENAME=kafka.truststore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=confluent
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=confluent
      - KAFKA_CFG_SSL_KEY_PASSWORD=confluent
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=JKS
      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=JKS
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://10.224.93.215:9092
      - KAFKA_ADVERTISED_LISTENERS=SSL://10.224.93.215:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL
#      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
#      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SSL_PRINCIPAL_MAPPING_RULES=RULE:^CN=(.*?),OU=TEST.*$$/$$1/,DEFAULT
      - KAFKA_SSL_CLIENT_AUTH=required
      - KAFKA_ZOOKEEPER_PROTOCOL=SSL
#      - KAFKA_ZOOKEEPER_USER=confluent
#      - KAFKA_ZOOKEEPER_PASSWORD=confluent
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=confluent
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=confluent
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
#      - KAFKA_CLIENT_USER=confluent
#      - KAFKA_CLIENT_PASSWORD=confluent
      - KAFKA_CERTIFICATE_PASSWORD=confluent
      - KAFKA_INTER_BROKER_LISTENER_NAME=SSL
      - KAFKA_OPTS=-Djavax.net.debug=all
    volumes:
      - ../../environment/2way-ssl/security:/bitnami/kafka/config/certs
```

If I go inside the directory `/bitnami/kafka/config/certs` and `/opt/bitnami/kafka/conf/certs/` I can find all the certificates files that are meant to be copied into container itself. 

Further if I check the server.properties file in `/opt/bitnami/kafka/conf/` I can see following properties are set : 
```

sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
sasl.mechanism.inter.broker.protocol=
ssl.client.auth=required
ssl.endpoint.identification.algorithm=""
ssl.keystore.filename=kafka.keystore.jks
ssl.keystore.location=/bitnami/kafka/config/certs/kafka.keystore.jks
ssl.keystore.password=confluent
ssl.keystore.type=JKS
ssl.key.password=confluent
ssl.principal.mapping.rules=RULE:^CN=(.*?),OU=TEST.*$/$1/,DEFAULT
ssl.truststore.filename=kafka.truststore.jks
ssl.truststore.location=/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.truststore.password=confluent
ssl.truststore.type=JKS
```

**Error**

![image](https://user-images.githubusercontent.com/17889806/142021726-60b95b0f-92b6-4d4a-9463-f8a05d51a364.png)

The error : `java.lang.IllegalArgumentException: Unable to auto-detect store file type from file name: /opt/bitnami/kafka/config/certs/` shows the file name is pointing to a directory rather than a certificate file.

Please help me out here.
