### ISSUE TITLE
Enable to secure Kafka cluster using SASL

### ISSUE THREAD

**Issue by springcomp** [bitnami/bitnami-docker-kafka#204]
**Description**

I’m trying to setup a quick POC kafka cluster that must be secured using SSL to then test my client processes and connectivity.
I have tried to follow very closely the instructions from the readme but I’m a newbie to Kafka in general and may have missed a lot of thing.

I was able to setup a quick cluster with no security using the baseline image from this repository. I was then able to create topics, publish and consume messages using the provided shell scripts inside the container. I was finally able to create my client, connect to the cluster and consume messages.

Now, I’m trying to secure the cluster using SSL to make this POC scenario closer to the target but find myself unable to succeed.

I get a message in the Kafka image:

> 

**Steps to reproduce the issue:**

1. Create the Kafka Cluster Configuration

Setup a new set of `keystore` and `truststore` files using the provided `kafka-generate-ssl.sh` script.
Use the following [docker-compose.yaml](https://gist.github.com/springcomp/739334728be1dc190bedecef82267827) file.

2. Run the Kafka Cluster

Start the image using `docker-compose up -d`.

3. Observe the logs

Run the following command:

```sh
docker-compose logs -f kafka
```

**Describe the results you received:**

The Kafka image is failing with errors like:

```
kafka_1      | Caused by: javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.
kafka_1      |  at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:73)
kafka_1      |  at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:136)
kafka_1      |  ... 20 more

```

**Describe the results you expected:**

I’m sure my configuration is incorrect but find myself unable to find the correct configuration.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.83GiB
 Name: docker-desktop
 ID: DNR6:4IOO:2QZQ:UF4V:GCWE:V742:AB7T:RUCQ:NEKD:3DKY:FGYD:EZ4W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Environment is: WSL2 on Windows 10.

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by juan131** [comment]
Hi @springcomp 

You're using **SSL** for "client" communications while using **SASL_SSL** for "external" communications. I can see under your environment section that you have the required env. vars to configure SSL but I'm missing the ones for configuring SASL. Could you try using the environment below?

```diff
    environment:
      # Configuration to connect with Zookeeper
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_PROTOCOL=PLAINTEXT
      # Kafka listeners/security configuration
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_SSL,EXTERNAL:SSL
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CERTIFICATE_PASSWORD=password
-     - KAFKA_SECURITY_PROTOCOL=SSL
+     - KAFKA_INTER_BROKER_USER=admin
+     - KAFKA_INTER_BROKER_PASSWORD=adminpassword
+     - KAFKA_CLIENT_USER=user
+     - KAFKA_CLIENT_PASSWORD=password
```

> Note: adapt the credentials according to your preferences.

Also, you're using persistence so don't forget to remove the volumes before trying your changes:

```console
$ docker-compose down -v
$ docker-compose up -d
```

**Comment by springcomp** [comment]
@juan131 thank for your feedback.

I have updated the [original gist](https://gist.github.com/springcomp/739334728be1dc190bedecef82267827) to incorporate your suggestions.
I had to keep the `KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT` line, however, otherwise, I got a complaint from the kafka process.

Still, it produces the same error as in the original post.

**Comment by springcomp** [comment]
> You're using **SSL** for "client" communications while using **SASL_SSL**

It seems there may be a confusion.
The following line definitely conveys my configuration:

```
KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_SSL,EXTERNAL:SSL
```

I understand this as using **SSL** for "external" and **SASL_SSL** for "client" - *i.e* the reverse of what you suggest.
Am I missing something ?

**Comment by juan131** [comment]
Hi @springcomp 

> I understand this as using SSL for "external" and SASL_SSL for "client" - i.e the reverse of what you suggest.
Am I missing something ?

You're right, sorry I stated it in the reverse way

> Still, it produces the same error as in the original post.

Did you remove the volumes as I suggested before retrying? Could you please share the logs you obtain?

**Comment by springcomp** [comment]
> Did you remove the volumes as I suggested before retrying? Could you please share the logs you obtain?

@juan131, indeed, I systematically remove the volume before any attempt.

Please, see the [log file](https://gist.github.com/springcomp/739334728be1dc190bedecef82267827#file-kafka_logs).
Zookeeper appear healthy.

**Comment by juan131** [comment]
Hi @springcomp 

One question about your scenario requirements: will your Kafka clients connect to the cluster from outside the Docker network? Or.. are they also containers running in Docker?

**Comment by springcomp** [comment]
> Hi @springcomp
> 
> One question about your scenario requirements: will your Kafka clients connect to the cluster from outside the Docker network? Or.. are they also containers running in Docker?

I’d like to explore both scenarios.
Let’s focus first on a client hosted and launched in the same Docker network using `docker-compose`.

**Comment by juan131** [comment]
All right!! Now I think I have the picture of what you're trying to achieve. Please give it a try with the docker-compose.yaml below:

```yaml
version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - 9094:9094
    volumes:
      - "kafka_data:/bitnami/kafka"
    environment:
      # Zookeeper configuration
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_PROTOCOL=PLAINTEXT
      # Kafka listeners / security configuration
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_SSL,EXTERNAL:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      - KAFKA_CLIENTS_USER=user
      - KAFKA_CLIENTS_PASSWORD=password
      - KAFKA_TLS_CLIENT_AUTH=none
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CERTIFICATE_PASSWORD=password
    volumes:
      - './kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

This is a test I did:

```console
$ docker-compose up -d && docker-compose logs -f
(...)
kafka_1      | [2021-11-23 07:43:11,169] INFO [KafkaServer id=1001] started (kafka.server.KafkaServer)
$ docker-compose exec kafka bash
I have no name!@011a85bac417:/$ export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf"
I have no name!@011a85bac417:/$ cat > /tmp/client.properties << EOF
security.protocol= SASL_SSL
sasl.mechanism=PLAIN
ssl.truststore.type=JKS
ssl.truststore.location=//opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.truststore.password=password
ssl.endpoint.identification.algorithm=
EOF
I have no name!@011a85bac417:/$ echo "Hello world" | kafka-console-producer.sh --producer.config /tmp/client.properties --broker-lisafka:9092 --topic test
I have no name!@011a85bac417:/$ kafka-console-consumer.sh --consumer.config /tmp/client.properties --bootstrap-server kafka:9092 --topic test --from-beginning

Hello world
```
