### ISSUE TITLE
Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available

### ISSUE THREAD

**Issue by a1b3rt** [bitnami/bitnami-docker-kafka#209]
Hi, I'm following the guide from - https://hub.docker.com/r/bitnami/kafka/

My `docker-compose.yml`

```yaml
version: "2"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    networks:
      - app-tier
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    networks:
      - app-tier
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

After running `docker-compose up -d`

```console
$ docker-compose up -d
Creating network "kafka_app-tier" with driver "bridge"
Creating kafka_zookeeper_1 ... done
Creating kafka_kafka_1     ... done
```

Then 

`$  docker run -it --rm --network app-tier bitnami/kafka:latest kafka-topics.sh --list  --bootstrap-server localhost:9092`

And this is what I'm getting

```
kafka 02:54:46.47
kafka 02:54:46.47 Welcome to the Bitnami kafka container
kafka 02:54:46.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 02:54:46.48 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 02:54:46.48

[2021-12-08 02:54:48,781] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```

What am I doing wrong? Thanks.
