### ISSUE TITLE
Cannot produce message to Kafka container from Windows host

### ISSUE THREAD

**Issue by charithf** [bitnami/bitnami-docker-kafka#21]
Hi,

I'm logging this issue just to get some support. I'm not sure whether this is a configuration issue.

- I am using https://github.com/bitnami/bitnami-docker-kafka
- I have created a simple zookeeper/kafka instance via docker-compose

```
services:
zookeeper:
image: 'bitnami/zookeeper:latest'
ports:
- '2181:2181'
volumes:
- 'C:/RandD/KafkaRun/bitnami2/zookeeper_data:/bitnami'
environment:
- ALLOW_ANONYMOUS_LOGIN=yes
kafka:
image: 'bitnami/kafka:latest'
ports:
- '9092:9092'
volumes:
- 'C:/RandD/KafkaRun/bitnami2/kafka_data:/bitnami'
environment:
- KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
- KAFKA_BROKER_ID=1
- KAFKA_LOG_RETENTION_HOURS=1
- ALLOW_PLAINTEXT_LISTENER=yes
```

From the host when i check the available topics list it works and shows me the list

I tried running the following command from windows host to produce 
%KAFKA_HOME%\bin\windows\kafka-console-producer.bat --broker-list localhost:9092 --topic audit21
I get the following error:
[2018-08-20 10:50:06,391] ERROR Error when sending message to topic audit21 with key: null, value: 19 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 2 record(s) for audit21-0: 2305 ms has passed since batch creation plus linger time

I'm not sure what i am doing wrong here as i have exposed/mapped the ports in the compose file

**Comment by codejnki** [comment]
This is probably not an ideal solution, but I was able to work around this.  I feel like the hosts file modification is a hack so if there is a better way to do this I'd like to know.

In my docker-compose.yml file I set up the following

```
  kafka:
    hostname: 'kafka'
    image: 'bitnami/kafka:2.0.0'
    ports:
      - '9092:9092'
    environment: 
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
```

In my hosts file I added an entry

```
127.0.0.1 kafka
```

Now local host applications and other containers in the same container network are able to connect to the kafka instance.

**Comment by charithf** [comment]
This solution is working. I'm wondering why. Usually in my other R&D tasks, I have managed to just expose the port and map to localhost and it works without a problem without changing the host file.

**Comment by codejnki** [comment]
I think it has to do with the way kafka specifically works and how kafka clients learn about the brokers.

When a kafka client connects you give it the --bootstrap.server option, then kafka tells the client about the names of the other machines.  Kafka by default gives out the host name.  If that hostname isn't resolvable outside the docker network, then bad times ensue.

**Comment by marcosbc** [comment]
Hi all, I'm glad you were able to resolve the issues! Kafka effectively needs its hostname to be resolvable inside the network.

In our README, we also recommend users to run the Docker image as client. This way you don't need to worry about downloading it locally and configuring it, and it is also directly inside your network.
Read more about it [here](https://github.com/bitnami/bitnami-docker-kafka/#step-3-launch-your-kafka-client-instance).

**Comment by cricket007** [comment]
Editing the hosts file is definitely a hack. You're supposed to expose two ports. One for internal Docker traffic, and another for external clients.

https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by marcosbc** [comment]
@cricket007 I remember it had something to do with how Kafka initializes, as it would use "kafka" as hostname but I did not inspect further. It could be possible the issue is with KAFKA_LISTENERS and KAFKA_ADVERTISED_LISTENERS not being set properly.

**Comment by cricket007** [comment]
Tested on Mac with these settings

  ```yaml
ports:
 - 9092
 - 29092
environment:
 ...
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
  KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
```

Producer, outside of container

```bash
$ kafka-console-producer --broker-list localhost:29092 --topic test
>hello world
[2018-11-01 17:45:16,135] WARN Error while fetching metadata with correlation id 1 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2018-11-01 17:45:16,247] WARN Error while fetching metadata with correlation id 3 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
>sample
>text
>interesting
```

And consumer outside of container

```bash
$ kafka-console-consumer --bootstrap-server localhost:29092 --topic test --from-beginning
hello world
sample
text
interesting
^CProcessed a total of 4 messages
```
