### ISSUE TITLE
Trouble running Docker Connect with docker-compose

### ISSUE THREAD

**Issue by behrangsa** [bitnami/bitnami-docker-kafka#212]
_NOTE: I tried to post my question on https://community.bitnami.com/ but I was directed to ask here instead._

**Description**

Can't add a Kafka Connect service to my Zookeeper/Kafka compose.

**Steps to reproduce the issue:**

1. Create a minimal docker compose that only contains Zookeeper and Kafka

This works with no problem:

```yaml
version: "2"

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.7
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    links:
      - zookeeper
```

2. Add a minimal Kafka Connect service to the composition:

```yaml
version: "2"

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.7
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    links:
      - zookeeper

  connect:
    image: debezium/connect:1.7.1.Final
    container_name: connect
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8093:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=kafka_connect_configs
      - OFFSET_STORAGE_TOPIC=kafka_connect_offsets
    links:
      - zookeeper
      - kafka
```

**Describe the results you received:**

Kafka Connect cannot connect to Kafka.

```
$ docker-compose up
...
connect      | 2021-12-13 23:09:19,871 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:19,973 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:20,074 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:20,375 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:20,777 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:21,679 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:22,582 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:23,686 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
connect      | 2021-12-13 23:09:24,589 WARN   ||  [AdminClient clientId=adminclient-1] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.   [org.apache.kafka.clients.NetworkClient]
```

**Describe the results you expected:**

Kafka Connect service/container to connect to the Kafka service/container. 

If I run the composition that only contains Zookeeper and Kafka and then run Connect on my local machine, it can connect to Kafka and work as expected:

```
[kafka_2.12-2.8.1] $ bin/connect-distributed.sh config/connect-distributed.properties 
...
[2021-12-14 11:32:16,791] INFO REST resources initialized; server is started and ready to handle requests (org.apache.kafka.connect.runtime.rest.RestServer:319)
[2021-12-14 11:32:16,791] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:57)
[2021-12-14 11:32:16,909] INFO Created topic (name=connect-offsets, numPartitions=25, replicationFactor=1, replicasAssignments=null, configs={cleanup.policy=compact}) on brokers at localhost:9092 (org.apache.kafka.connect.util.TopicAdmin:389)
...
[2021-12-14 11:32:17,677] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connectors and tasks using config offset -1 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1244)
[2021-12-14 11:32:17,677] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1272)
[2021-12-14 11:32:17,718] INFO [Worker clientId=connect-1, groupId=connect-cluster] Session key updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1587)


[kafka_2.12-2.8.1] $ curl -s localhost:8083 | jq
{
  "version": "2.8.1",
  "commit": "839b886f9b732b15",
  "kafka_cluster_id": "2nE5XZWaQYiodNp5UYR8JA"
}

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
$ docker --version
Docker version 20.10.12, build e91ed57
```

- Output of `docker info`:

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 66
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-41-generic
 Operating System: Linux Mint 20.2
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 62.68GiB
 Name: ...
 ID: 5A5J:KS5S:RVUQ:PFV2:YSS2:2WT7:C2KD:SK3H:PVCJ:7NJO:HLF7:FB6E
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

N/A
