### ISSUE TITLE
[IMPROVEMENT] Support of min.insync.replicas configuration in parameters

### ISSUE THREAD

**Issue by jaudiger** [bitnami/bitnami-docker-kafka#217]
**Description**

I would like to have a parameter to override the [min.insync.replicas](https://kafka.apache.org/documentation/#brokerconfigs_min.insync.replicas) configuration. Currently, the only way to do it is to have an extra environment variable to set it.

The environment variable fulfills my use case, I just wanted to have everything set with the chart's parameters. This is a minor improvement.

**Describe the results you received:**

```yml
extraEnvVars:
  - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
    value: "1"
```

**Describe the results you expected:**

```yml
minInsyncReplicas: 1
```
