### ISSUE TITLE
Not connect external or internal client kafka with this docker-compose 

### ISSUE THREAD

**Issue by mohamadmazaheri** [bitnami/bitnami-docker-kafka#219]
Hi, I am using Windows 10, most of all isuues and answre related to Linux that they do not help me.

This command line work for me and I created topic, consumer and producer perfectly:
```
Create Network:
docker network create app --driver bridge

Docker Run Zookeeper:
docker run -d --name zookeeper --network app -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest

Docker Run Kafka:
docker run -d --name kafka --network app -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest

Docker GetIp Kafka:
docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kafka

Docker Get List Topics:
docker run -it --rm --network app -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest kafka-topics.sh --list  --bootstrap-server kafka:9092

Docker Add Topic:
docker run -it --rm --network app -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest kafka-topics.sh --create  --replication-factor 1 --partitions 1 --topic test --bootstrap-server kafka:9092

Docker Add Producer:
docker run -it --rm --network app -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest kafka-console-producer.sh --topic test  --broker-list kafka:9092

Docker Add Consumer:
docker run -it --rm --network app -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest kafka-console-consumer.sh --topic test --from-beginning --bootstrap-server kafka:9092
```

But my probles not connect external to kafka container.
I read document of bitnami/kafka for internal and external clients and use this docker-compose.yml

```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
```

But when run kafka server, i dont have use kafka server to create topic or consumer and producer.
I tried a lot and tried different queries, but each one makes a mistake.

My test queries in cmd and error:
`docker run -it --rm -e KAFKA_CFG_ZOOKEEPER_CONNECT=172.26.0.2:2181 bitnami/kafka:latest kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9093 --topic test --from-beginning`
or
`docker run -it --rm -e KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper_1:2181 bitnami/kafka:latest kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9093 --topic test --from-beginning
`
> [2022-01-19 00:54:01,131] WARN [Consumer clientId=consumer-console-consumer-88991-1, groupId=console-consumer-88991] Connection to node -1 (/127.0.0.1:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
> [2022-01-19 00:54:01,132] WARN [Consumer clientId=consumer-console-consumer-88991-1, groupId=console-consumer-88991] Bootstrap broker 127.0.0.1:9093 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)

`docker run -it --rm -e KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper_1:2181 bitnami/kafka:latest kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning`
or
`docker run -it --rm -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning`

> [2022-01-19 01:19:15,638] WARN Couldn't resolve server kafka:9092 from bootstrap.servers as DNS resolution failed for kafka (org.apache.kafka.clients.ClientUtils)
> [2022-01-19 01:19:15,645] ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$)
> org.apache.kafka.common.KafkaException: Failed to construct kafka consumer

Please help me what is rung?

For more detail my NetworkSetting: 

> zookeeper:
>         "NetworkSettings": {
>             "Ports": {
>                 "2181/tcp": [
>                     {
>                         "HostIp": "0.0.0.0",
>                         "HostPort": "2181"
>                     }
>                 ],
>                 "2888/tcp": null,
>                 "3888/tcp": null,
>                 "8080/tcp": null
>             },
>             "Networks": {
>                     "Gateway": "172.26.0.1",
>                     "IPAddress": "172.26.0.2",
>                 }
>             } 
> kafka:
>         "NetworkSettings": {
>             "Ports": {
>                 "9092/tcp": [
>                     {
>                         "HostIp": "0.0.0.0",
>                         "HostPort": "9092"
>                     }
>                 ],
>                 "9093/tcp": [
>                     {
>                         "HostIp": "0.0.0.0",
>                         "HostPort": "9093"
>                     }
>                 ]
>             },
>             "Networks": {
>                     "Gateway": "172.26.0.1",
>                     "IPAddress": "172.26.0.3",
>                 }
>             }
