### ISSUE TITLE
Enable JMX polling?

### ISSUE THREAD

**Issue by jmrichardson** [bitnami/bitnami-docker-kafka#22]
Hi, how do you enable jmx monitoring?  I am trying to use kafka-manager with bitnami docker kafka but I am not sure how to set the environment varilable JMX_PORT.  I am referencing this post on how to set the environment variable:

https://github.com/yahoo/kafka-manager/issues/187

**Comment by marcosbc** [comment]
Hi @jmrichardson, you can set the JMX_PORT environment variable as following, if you are using Docker compose:

```
version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '23456:23456'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=23456
```

That would configure Kafka to use port 23456 for JMX, and expose it.
