### ISSUE TITLE
Kafka exits with code 1 without error Message

### ISSUE THREAD

**Issue by Ch33s3Burger** [bitnami/bitnami-docker-kafka#220]
**Description**

I created a docker-compose with zookeeper and kafka. The smaller one without using SASL_SSL works fine. 

```yaml
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
```

When I try to add security, Kafka exits with code 1 without an error message. I even tried to change the log level.

```yaml
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
#      - ZOO_ENABLE_AUTH=yes
#      - ZOO_SERVER_USERS=kafka
#      - ZOO_SERVER_PASSWORDS=kafka_password
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
#      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

#      - KAFKA_CFG_LISTENERS=SSL://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://:9092

#      - KAFKA_ZOOKEEPER_USER=kafka
#      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_CLIENT_USER=user
      - KAFKA_CLIENT_PASSWORD=password

      - KAFKA_CERTIFICATE_PASSWORD=cert_password
      - KAFKA_TLS_TYPE=JKS # or PEM

#      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_ZOOKEEPER_PROTOCOL=SSL

      - KAFKA_LOG4J_LOGGERS="kafka.controller=TRACE,kafka.request.logger=TRACE"
      - KAFKA_LOG4J_ROOT_LOGLEVEL=TRACE
      - KAFKA_TOOLS_LOG4J_LOGLEVEL=TRACE
    depends_on:
      - zookeeper
    volumes:
      - './keystore/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './truststore/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro'

      - './truststore/zookeeper.truststore.jks:/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro'
      - './keystore/zookeeper.keystore.jks:/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro'`
```

**Steps to reproduce the issue:**

1. create docker-compose.yml with the configurations above.
2. run docker-compose up

**Describe the results you received:**

My Logs look like the following:

```
Starting kafkawithzookeeper_zookeeper_1 ... done
Starting kafkawithzookeeper_kafka_1     ... done
Attaching to kafkawithzookeeper_zookeeper_1, kafkawithzookeeper_kafka_1
kafka_1      | kafka 09:55:48.06 
kafka_1      | kafka 09:55:48.06 Welcome to the Bitnami kafka container
zookeeper_1  | zookeeper 09:55:47.69 
kafka_1      | kafka 09:55:48.06 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
zookeeper_1  | zookeeper 09:55:47.69 Welcome to the Bitnami zookeeper container
zookeeper_1  | zookeeper 09:55:47.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
kafka_1      | kafka 09:55:48.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
zookeeper_1  | zookeeper 09:55:47.69 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
kafka_1      | kafka 09:55:48.07 
zookeeper_1  | zookeeper 09:55:47.69 
zookeeper_1  | zookeeper 09:55:47.69 INFO  ==> ** Starting ZooKeeper setup **
zookeeper_1  | zookeeper 09:55:47.72 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
zookeeper_1  | zookeeper 09:55:47.74 INFO  ==> Initializing ZooKeeper...
zookeeper_1  | zookeeper 09:55:47.74 INFO  ==> User injected custom configuration detected!
kafka_1      | kafka 09:55:48.07 INFO  ==> ** Starting Kafka setup **
zookeeper_1  | zookeeper 09:55:47.74 INFO  ==> Deploying ZooKeeper with persisted data...
zookeeper_1  | zookeeper 09:55:47.74 INFO  ==> ** ZooKeeper setup finished! **
zookeeper_1  | 
zookeeper_1  | zookeeper 09:55:47.75 INFO  ==> ** Starting ZooKeeper **
zookeeper_1  | /opt/bitnami/java/bin/java
zookeeper_1  | ZooKeeper JMX enabled by default
zookeeper_1  | Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
kafka_1      | kafka 09:55:48.14 INFO  ==> Initializing Kafka...
zookeeper_1  | 2022-01-21 09:55:48,145 [myid:] - INFO  [main:QuorumPeerConfig@174] - Reading configuration from: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
kafka_1      | kafka 09:55:48.14 INFO  ==> No injected configuration files found, creating default config files
zookeeper_1  | 2022-01-21 09:55:48,154 [myid:] - INFO  [main:QuorumPeerConfig@444] - clientPortAddress is 0.0.0.0:2181
zookeeper_1  | 2022-01-21 09:55:48,154 [myid:] - INFO  [main:QuorumPeerConfig@448] - secureClientPort is not set
zookeeper_1  | 2022-01-21 09:55:48,154 [myid:] - INFO  [main:QuorumPeerConfig@464] - observerMasterPort is not set
zookeeper_1  | 2022-01-21 09:55:48,155 [myid:] - INFO  [main:QuorumPeerConfig@481] - metricsProvider.className is org.apache.zookeeper.metrics.impl.DefaultMetricsProvider
zookeeper_1  | 2022-01-21 09:55:48,158 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
zookeeper_1  | 2022-01-21 09:55:48,158 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
zookeeper_1  | 2022-01-21 09:55:48,158 [myid:1] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
zookeeper_1  | 2022-01-21 09:55:48,158 [myid:1] - WARN  [main:QuorumPeerMain@139] - Either no config or no quorum defined in config, running in standalone mode
zookeeper_1  | 2022-01-21 09:55:48,160 [myid:1] - INFO  [main:ManagedUtil@44] - Log4j 1.2 jmx support found and enabled.
zookeeper_1  | 2022-01-21 09:55:48,166 [myid:1] - INFO  [main:QuorumPeerConfig@174] - Reading configuration from: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
zookeeper_1  | 2022-01-21 09:55:48,167 [myid:1] - INFO  [main:QuorumPeerConfig@444] - clientPortAddress is 0.0.0.0:2181
zookeeper_1  | 2022-01-21 09:55:48,167 [myid:1] - INFO  [main:QuorumPeerConfig@448] - secureClientPort is not set
zookeeper_1  | 2022-01-21 09:55:48,167 [myid:1] - INFO  [main:QuorumPeerConfig@464] - observerMasterPort is not set
zookeeper_1  | 2022-01-21 09:55:48,167 [myid:1] - INFO  [main:QuorumPeerConfig@481] - metricsProvider.className is org.apache.zookeeper.metrics.impl.DefaultMetricsProvider
zookeeper_1  | 2022-01-21 09:55:48,167 [myid:1] - INFO  [main:ZooKeeperServerMain@123] - Starting server
zookeeper_1  | 2022-01-21 09:55:48,176 [myid:1] - INFO  [main:ServerMetrics@62] - ServerMetrics initialized with provider org.apache.zookeeper.metrics.impl.DefaultMetricsProvider@574b560f
zookeeper_1  | 2022-01-21 09:55:48,178 [myid:1] - INFO  [main:DigestAuthenticationProvider@47] - ACL digest algorithm is: SHA1
zookeeper_1  | 2022-01-21 09:55:48,178 [myid:1] - INFO  [main:DigestAuthenticationProvider@61] - zookeeper.DigestAuthenticationProvider.enabled = true
zookeeper_1  | 2022-01-21 09:55:48,179 [myid:1] - INFO  [main:FileTxnSnapLog@124] - zookeeper.snapshot.trust.empty : false
zookeeper_1  | 2022-01-21 09:55:48,187 [myid:1] - INFO  [main:ZookeeperBanner@42] - 
zookeeper_1  | 2022-01-21 09:55:48,187 [myid:1] - INFO  [main:ZookeeperBanner@42] -   ______                  _                                          
zookeeper_1  | 2022-01-21 09:55:48,187 [myid:1] - INFO  [main:ZookeeperBanner@42] -  |___  /                 | |                                         
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] -     / /    ___     ___   | | __   ___    ___   _ __     ___   _ __   
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] -    / /    / _ \   / _ \  | |/ /  / _ \  / _ \ | '_ \   / _ \ | '__|
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] -   / /__  | (_) | | (_) | |   <  |  __/ |  __/ | |_) | |  __/ | |    
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] -  /_____|  \___/   \___/  |_|\_\  \___|  \___| | .__/   \___| |_|
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] -                                               | |                     
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] -                                               |_|                     
zookeeper_1  | 2022-01-21 09:55:48,188 [myid:1] - INFO  [main:ZookeeperBanner@42] - 
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:zookeeper.version=3.7.0-e3704b390a6697bfdf4b0bef79e3da7a4f6bac4b, built on 2021-03-17 09:46 UTC
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:host.name=6e5962f057b4
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.version=11.0.13
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.vendor=BellSoft
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.home=/opt/bitnami/java
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.class.path=/opt/bitnami/zookeeper/bin/../zookeeper-server/target/classes:/opt/bitnami/zookeeper/bin/../build/classes:/opt/bitnami/zookeeper/bin/../zookeeper-server/target/lib/*.jar:/opt/bitnami/zookeeper/bin/../build/lib/*.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-prometheus-metrics-3.7.0.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-jute-3.7.0.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-3.7.0.jar:/opt/bitnami/zookeeper/bin/../lib/snappy-java-1.1.7.7.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-log4j12-1.7.30.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-api-1.7.30.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_servlet-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_hotspot-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient_common-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/simpleclient-0.9.0.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-unix-common-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-epoll-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-resolver-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-handler-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-common-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-codec-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-buffer-4.1.59.Final.jar:/opt/bitnami/zookeeper/bin/../lib/metrics-core-4.1.12.1.jar:/opt/bitnami/zookeeper/bin/../lib/log4j-1.2.17.jar:/opt/bitnami/zookeeper/bin/../lib/jline-2.14.6.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-ajax-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-servlet-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-server-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-security-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-io-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-http-9.4.38.v20210224.jar:/opt/bitnami/zookeeper/bin/../lib/javax.servlet-api-3.1.0.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-databind-2.10.5.1.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-core-2.10.5.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-annotations-2.10.5.jar:/opt/bitnami/zookeeper/bin/../lib/commons-cli-1.4.jar:/opt/bitnami/zookeeper/bin/../lib/audience-annotations-0.12.0.jar:/opt/bitnami/zookeeper/bin/../zookeeper-*.jar:/opt/bitnami/zookeeper/bin/../zookeeper-server/src/main/resources/lib/*.jar:/opt/bitnami/zookeeper/bin/../conf:
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.io.tmpdir=/tmp
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:java.compiler=<NA>
zookeeper_1  | 2022-01-21 09:55:48,189 [myid:1] - INFO  [main:Environment@98] - Server environment:os.name=Linux
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:os.arch=amd64
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:os.version=5.4.0-94-generic
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:user.name=?
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:user.home=?
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:user.dir=/
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:os.memory.free=1009MB
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:os.memory.max=1024MB
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:Environment@98] - Server environment:os.memory.total=1024MB
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@138] - zookeeper.enableEagerACLCheck = false
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@151] - zookeeper.digest.enabled = true
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@155] - zookeeper.closeSessionTxn.enabled = true
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@1499] - zookeeper.flushDelay=0
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@1508] - zookeeper.maxWriteQueuePollTime=0
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@1517] - zookeeper.maxBatchSize=1000
zookeeper_1  | 2022-01-21 09:55:48,190 [myid:1] - INFO  [main:ZooKeeperServer@260] - zookeeper.intBufferStartingSizeBytes = 1024
zookeeper_1  | 2022-01-21 09:55:48,191 [myid:1] - INFO  [main:BlueThrottle@141] - Weighed connection throttling is disabled
zookeeper_1  | 2022-01-21 09:55:48,192 [myid:1] - INFO  [main:ZooKeeperServer@1300] - minSessionTimeout set to 4000
zookeeper_1  | 2022-01-21 09:55:48,192 [myid:1] - INFO  [main:ZooKeeperServer@1309] - maxSessionTimeout set to 40000
zookeeper_1  | 2022-01-21 09:55:48,193 [myid:1] - INFO  [main:ResponseCache@45] - getData response cache size is initialized with value 400.
zookeeper_1  | 2022-01-21 09:55:48,193 [myid:1] - INFO  [main:ResponseCache@45] - getChildren response cache size is initialized with value 400.
zookeeper_1  | 2022-01-21 09:55:48,193 [myid:1] - INFO  [main:RequestPathMetricsCollector@109] - zookeeper.pathStats.slotCapacity = 60
zookeeper_1  | 2022-01-21 09:55:48,193 [myid:1] - INFO  [main:RequestPathMetricsCollector@110] - zookeeper.pathStats.slotDuration = 15
zookeeper_1  | 2022-01-21 09:55:48,193 [myid:1] - INFO  [main:RequestPathMetricsCollector@111] - zookeeper.pathStats.maxDepth = 6
zookeeper_1  | 2022-01-21 09:55:48,194 [myid:1] - INFO  [main:RequestPathMetricsCollector@112] - zookeeper.pathStats.initialDelay = 5
zookeeper_1  | 2022-01-21 09:55:48,194 [myid:1] - INFO  [main:RequestPathMetricsCollector@113] - zookeeper.pathStats.delay = 5
zookeeper_1  | 2022-01-21 09:55:48,194 [myid:1] - INFO  [main:RequestPathMetricsCollector@114] - zookeeper.pathStats.enabled = false
zookeeper_1  | 2022-01-21 09:55:48,195 [myid:1] - INFO  [main:ZooKeeperServer@1536] - The max bytes for all large requests are set to 104857600
zookeeper_1  | 2022-01-21 09:55:48,196 [myid:1] - INFO  [main:ZooKeeperServer@1550] - The large request threshold is set to -1
zookeeper_1  | 2022-01-21 09:55:48,196 [myid:1] - INFO  [main:AuthenticationHelper@66] - zookeeper.enforce.auth.enabled = false
zookeeper_1  | 2022-01-21 09:55:48,196 [myid:1] - INFO  [main:AuthenticationHelper@67] - zookeeper.enforce.auth.schemes = []
zookeeper_1  | 2022-01-21 09:55:48,196 [myid:1] - INFO  [main:ZooKeeperServer@361] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 clientPortListenBacklog -1 datadir /bitnami/zookeeper/data/version-2 snapdir /bitnami/zookeeper/data/version-2
zookeeper_1  | 2022-01-21 09:55:48,215 [myid:1] - INFO  [main:Log@169] - Logging initialized @426ms to org.eclipse.jetty.util.log.Slf4jLog
kafka_1      | kafka 09:55:48.22 INFO  ==> Configuring Kafka for inter-broker communications with SSL authentication.
zookeeper_1  | 2022-01-21 09:55:48,271 [myid:1] - WARN  [main:ContextHandler@1660] - o.e.j.s.ServletContextHandler@50378a4{/,null,STOPPED} contextPath ends with /*
zookeeper_1  | 2022-01-21 09:55:48,272 [myid:1] - WARN  [main:ContextHandler@1671] - Empty contextPath
zookeeper_1  | 2022-01-21 09:55:48,286 [myid:1] - INFO  [main:Server@375] - jetty-9.4.38.v20210224; built: 2021-02-24T20:25:07.675Z; git: 288f3cc74549e8a913bf363250b0744f2695b8e6; jvm 11.0.13+8-LTS
zookeeper_1  | 2022-01-21 09:55:48,314 [myid:1] - INFO  [main:DefaultSessionIdManager@334] - DefaultSessionIdManager workerName=node0
zookeeper_1  | 2022-01-21 09:55:48,314 [myid:1] - INFO  [main:DefaultSessionIdManager@339] - No SessionScavenger set, using defaults
zookeeper_1  | 2022-01-21 09:55:48,315 [myid:1] - INFO  [main:HouseKeeper@132] - node0 Scavenging every 660000ms
kafka_1      | kafka 09:55:48.31 INFO  ==> Configuring Kafka for client communications with SASL_SSL authentication.
zookeeper_1  | 2022-01-21 09:55:48,319 [myid:1] - WARN  [main:ConstraintSecurityHandler@759] - ServletContext@o.e.j.s.ServletContextHandler@50378a4{/,null,STARTING} has uncovered http methods for path: /*
zookeeper_1  | 2022-01-21 09:55:48,325 [myid:1] - INFO  [main:ContextHandler@916] - Started o.e.j.s.ServletContextHandler@50378a4{/,null,AVAILABLE}
kafka_1      | kafka 09:55:48.32 INFO  ==> Custom JAAS authentication file detected. Skipping generation.
kafka_1      | kafka 09:55:48.32 WARN  ==> The following environment variables will be ignored: KAFKA_CLIENT_USERS, KAFKA_CLIENT_PASSWORDS, KAFKA_INTER_BROKER_USER, KAFKA_INTER_BROKER_PASSWORD, KAFKA_ZOOKEEPER_USER and KAFKA_ZOOKEEPER_PASSWORD
kafka_1      | kafka 09:55:48.32 INFO  ==> Creating users in Zookeeper
zookeeper_1  | 2022-01-21 09:55:48,337 [myid:1] - INFO  [main:AbstractConnector@331] - Started ServerConnector@cc43f62{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
zookeeper_1  | 2022-01-21 09:55:48,337 [myid:1] - INFO  [main:Server@415] - Started @549ms
zookeeper_1  | 2022-01-21 09:55:48,338 [myid:1] - INFO  [main:JettyAdminServer@181] - Started AdminServer on address 0.0.0.0, port 8080 and command URL /commands
zookeeper_1  | 2022-01-21 09:55:48,341 [myid:1] - INFO  [main:ServerCnxnFactory@169] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
zookeeper_1  | 2022-01-21 09:55:48,341 [myid:1] - WARN  [main:ServerCnxnFactory@309] - maxCnxns is not configured, using default value 0.
zookeeper_1  | 2022-01-21 09:55:48,342 [myid:1] - INFO  [main:NIOServerCnxnFactory@652] - Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 12 worker threads, and 64 kB direct buffers.
zookeeper_1  | 2022-01-21 09:55:48,343 [myid:1] - INFO  [main:NIOServerCnxnFactory@660] - binding to port 0.0.0.0/0.0.0.0:2181
zookeeper_1  | 2022-01-21 09:55:48,355 [myid:1] - INFO  [main:WatchManagerFactory@42] - Using org.apache.zookeeper.server.watch.WatchManager as watch manager
zookeeper_1  | 2022-01-21 09:55:48,355 [myid:1] - INFO  [main:WatchManagerFactory@42] - Using org.apache.zookeeper.server.watch.WatchManager as watch manager
zookeeper_1  | 2022-01-21 09:55:48,356 [myid:1] - INFO  [main:ZKDatabase@133] - zookeeper.snapshotSizeFactor = 0.33
zookeeper_1  | 2022-01-21 09:55:48,356 [myid:1] - INFO  [main:ZKDatabase@153] - zookeeper.commitLogCount=500
zookeeper_1  | 2022-01-21 09:55:48,358 [myid:1] - INFO  [main:SnapStream@61] - zookeeper.snapshot.compression.method = CHECKED
zookeeper_1  | 2022-01-21 09:55:48,358 [myid:1] - INFO  [main:FileSnap@85] - Reading snapshot /bitnami/zookeeper/data/version-2/snapshot.1e
zookeeper_1  | 2022-01-21 09:55:48,361 [myid:1] - INFO  [main:DataTree@1716] - The digest value is empty in snapshot
zookeeper_1  | 2022-01-21 09:55:48,365 [myid:1] - INFO  [main:ZKDatabase@290] - Snapshot loaded in 9 ms, highest zxid is 0x1e, digest is 59675028167
zookeeper_1  | 2022-01-21 09:55:48,367 [myid:1] - INFO  [main:FileTxnSnapLog@479] - Snapshotting: 0x1e to /bitnami/zookeeper/data/version-2/snapshot.1e
zookeeper_1  | 2022-01-21 09:55:48,369 [myid:1] - INFO  [main:ZooKeeperServer@543] - Snapshot taken in 2 ms
zookeeper_1  | 2022-01-21 09:55:48,375 [myid:1] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@137] - PrepRequestProcessor (sid:0) started, reconfigEnabled=false
zookeeper_1  | 2022-01-21 09:55:48,376 [myid:1] - INFO  [main:RequestThrottler@75] - zookeeper.request_throttler.shutdownTimeout = 10000
zookeeper_1  | 2022-01-21 09:55:48,386 [myid:1] - INFO  [main:ContainerManager@84] - Using checkIntervalMs=60000 maxPerMinute=10000 maxNeverUsedIntervalMs=0
zookeeper_1  | 2022-01-21 09:55:48,387 [myid:1] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
kafkawithzookeeper_kafka_1 exited with code 1
```
