### ISSUE TITLE
cannot create directory '/bitnami/kafka/config': Permission denied

### ISSUE THREAD

**Issue by ang00** [bitnami/bitnami-docker-kafka#227]
### Name and Version

bitnami/bitnami-docker-kafka:latest

### What steps will reproduce the bug?

docker dot run, cannot create directory '/bitnami/kafka/config': Permission denied 

### What do you see instead?

* docker-compose
```yml
  kafka:
    image: bitnami/kafka
    networks:
      - mogo-net
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    expose:
      - 9092
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - ./data/kafka:/bitnami/kafka
  ```
* error log
```shell
kafka 15:23:22.71
kafka 15:23:22.71 Welcome to the Bitnami kafka container
kafka 15:23:22.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 15:23:22.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 15:23:22.71
kafka 15:23:22.72 INFO  ==> ** Starting Kafka setup **

### Additional information

_No response_
