### ISSUE TITLE
Unable to start KAFKA

### ISSUE THREAD

**Issue by Phanikumarg1981** [bitnami/bitnami-docker-kafka#228]
### Name and Version

Bitnami/3.1.0-debian-10-r25

### What steps will reproduce the bug?

Created certs using provided script.
Copied Certs to this folder: /opt/bitnami/kafka/config/certs

Run the Compose file provided in document:
```
version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_CLIENT_USER=user
      - KAFKA_CLIENT_PASSWORD=password
      - KAFKA_CERTIFICATE_PASSWORD=Phani@123
      - KAFKA_TLS_TYPE=JKS # or PEM
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - ALLOW_PLAINTEXT_LISTENER=NO
    volumes:
      - './kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
```
Error:

Kafka is not starting 
The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure a secure protocol. Set the environment variable ALLOW_PLAINTEXT_LISTENER=yes to allow the container to be started with a plaintext listener. This is only recommended for development.

![error](https://user-images.githubusercontent.com/39512363/155280432-06268703-9dc5-4768-8ec7-92b790739664.png)

### What is the expected behavior?

Kafka and zookeeper images should build ..

### What do you see instead?

Kafka is not starting.
![error](https://user-images.githubusercontent.com/39512363/155280485-4df7fa30-e525-4c24-9c7f-575194e1b528.png)
