### ISSUE TITLE
ACL create with sasl_plaintext and sasl_ssl

### ISSUE THREAD

**Issue by mohsraj** [bitnami/bitnami-docker-kafka#237]
### Name and Version

3

### What steps will reproduce the bug?

I've run a kafka container with sasl_plaintext activated for port 9092 and sasl_ssl for port 9093, all is OK and I can produce and consume on both ports.

Yet, I'm not able to create new acls, when I'm trying 
```
export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf"
kafka-acls.sh --bootstrap-server=kafka-1:9092 --add --allow-principal User:admin --operation Read --group=* --topic test
```
I can the following error in Kafak-1 logs
```
kafka-1          | [2022-03-16 11:05:29,035] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1001] Failed authentication with /172.25.0.5 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
```
My jaas file 
```
external.KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_readera="readera-secret"
    user_writera="writera-secret";
};

internal.KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret";
};
```
My compose file
```yaml
  zookeeper:
    image: docker.io/bitnami/zookeeper:${Zookeeper_VERSION}
    container_name: zookeeper
    hostname: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
    networks:
      - kafka_network
      - elk
      
  kafka-1:
    image: docker.io/bitnami/kafka:${Kafka_VERSION}
    container_name: kafka-1
    hostname: kafka-1
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/bitnami
      - ./secrets/messaging/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - ./secrets/messaging/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - ./secrets/messaging/kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
      - ./secrets/messaging/kafka_client_jaas.conf:/opt/bitnami/kafka/config/kafka_client_jaas.conf
      - ./secrets/messaging/internal.properties:/opt/bitnami/kafka/config/cli.int.properties
      - ./secrets/messaging/external.properties:/opt/bitnami/kafka/config/cli.ext.properties
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_SSL
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://192.168.56.103:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL  
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CLIENT_USERS: admin
      KAFKA_CLIENT_PASSWORDS: admin-secret
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: Pas123
      KAFKA_CFG_SSL_KEY_PASSWORD: Pas123
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: Pas123
      KAFKA_CFG_SSL_CLIENT_AUTH: requested
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_CFG_SUPER_USERS: User:admin;User:kafka 
      KAFKA_CFG_LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG
    depends_on:
      - zookeeper
    networks:
      - kafka_network
      - elk
```

### What do you see instead?

I'm getting an error
