### ISSUE TITLE
Kafka container stops

### ISSUE THREAD

**Issue by K2ouMais** [bitnami/bitnami-docker-kafka#252]
### Name and Version

bitnami/kafka:latest

### What steps will reproduce the bug?

docker-compose.yml

```yaml
version: '3.8'
services:

    kafka:
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        volumes:
            - "kafka_data:/bitnami"
        networks:
            - network
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
            - ALLOW_PLAINTEXT_LISTENER=yes

networks:
    network:
        driver: bridge
volumes:
    kafka_data:
        driver: local
```

After running ```docker-compose up -d``` seems that the container stops itself.

### What is the expected behavior?

I want the container to stay up and running.

### What do you see instead?

Docker seems to start the container and it shuts it down again.

### Additional information

Log:
```
kafka 13:14:09.70 
kafka 13:14:09.70 Welcome to the Bitnami kafka container
kafka 13:14:09.70 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 13:14:09.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 13:14:09.71 
kafka 13:14:09.71 INFO  ==> ** Starting Kafka setup **
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_BROKER_ID Must match what is set in KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_CONTROLLER_QUORUM_VOTERS must match brokers set with KAFKA_CFG_BROKER_ID
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_PROCESS_ROLES must include 'controller' for KRaft
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka 13:14:09.77 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 13:14:09.78 INFO  ==> Initializing Kafka...
kafka 13:14:09.78 INFO  ==> No injected configuration files found, creating default config files
kafka 13:14:09.94 INFO  ==> Initializing KRaft...
kafka 13:14:09.95 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka 13:14:11.50 INFO  ==> Generated Kafka cluster ID 'yYisgVl9SBqvRloSuvqgKw'
kafka 13:14:11.51 INFO  ==> Formatting storage directories to add metadata...
```

Nothing more happens.
