### ISSUE TITLE
Cant produce messages on kafka container from external containers.

### ISSUE THREAD

**Issue by K2ouMais** [bitnami/bitnami-docker-kafka#256]
### Name and Version

bitnami/kafka:latest

### What steps will reproduce the bug?

Kafka Containers
```
version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9999:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

Now I have another project running in containers and these are trying to produce messages on ```localhost:9093```.

I get an exception because it seems it cant connect to kafka.

### What is the expected behavior?

I expect to connect to kafka and produce a message on a simple topic.

### What do you see instead?

Instead I see Exceptions and seems that I cant connect at all.

### Additional information

I am pretty sure, this have something to do with the configuration and I need some help here.

Thank you in advance

If I put the kafka containers on the docker-compose of my project, everything seems to work, but I want the kafka containers to be its own project, so that I can test producing and consuming messages.
