### ISSUE TITLE
inconsistent paths to Kafka server configuration file (server.properties)

### ISSUE THREAD

**Issue by progaddict** [bitnami/bitnami-docker-kafka#263]
### Name and Version

bitnami/kafka:3.2.0

### What steps will reproduce the bug?

Example docker compose excerpt:
```
  kafka:
    image: bitnami/kafka:3.2.0
    ports:
      - "9093:9093"
    environment:
      - BITNAMI_DEBUG=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./config/kafka/server.properties:/opt/bitnami/kafka/config/server.properties:ro
```

### What is the expected behavior?

Kafka server starts and uses the mounted properties.

### What do you see instead?

Error message in logs:

```
kafka 14:28:48.43 INFO  ==> Initializing Kafka...
kafka 14:28:48.43 INFO  ==> No injected configuration files found, creating default config files
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/kafka/config/server.properties: Read-only file system
```

### Additional information

So the problem is that [libkafka.sh](https://github.com/bitnami/bitnami-docker-kafka/blob/e6a63b0902adac99fd57be21e893b25d9fb578cf/3.2/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L776) uses `"$KAFKA_BASE_DIR"/conf/server.properties` when it checks for the server configuration file but [kafka-env.sh](https://github.com/bitnami/bitnami-docker-kafka/blob/e6a63b0902adac99fd57be21e893b25d9fb578cf/3.2/debian-11/rootfs/opt/bitnami/scripts/kafka-env.sh#L72) sets up actually a different path for configuration (`"${KAFKA_BASE_DIR}/config"`).

I.e. one script uses `conf` and the other one `config` directory.

Current workaround would probably be to mount the configuration file to both paths (I haven't tested that yet...):
```
    volumes:
      - ./config/kafka/server.properties:/opt/bitnami/kafka/conf/server.properties:ro
      - ./config/kafka/server.properties:/opt/bitnami/kafka/config/server.properties:ro
```

It would be really great if you could fix this inconsistency in paths to the configuration directory. Thank you!
