### ISSUE TITLE
External & internal connections setup doesn't work

### ISSUE THREAD

**Issue by denis-zhdanov** [bitnami/bitnami-docker-kafka#29]
Hello,

Could you please help me with setting up bitnami kafka docker in a way to access it either from docker or host networks?  

My use-case is to test docker image during CI. I.e. run docker with kafka, zookeeper, target application and then perform the test by sending particular messages to kafka and verifying that there is particular output in kafka.

[Here](https://github.com/denis-zhdanov/samples/tree/master/docker/kafka) is a complete standalone example which illustrates the problem:
- [simple kafka client](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/src/main/java/org/denis/KafkaMessageHandler.java) which receives a message in one topic and publishes an echo message to another one
- [docker-compose](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/docker-compose-bitnami.yml) which configures *kafka* container to be exposed either to docker or host networks
- [a test](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/src/test/java/org/denis/ApplicationTest.java) which tries to send a message to a kafka running in docker

There is a [script](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/run-bitnami.sh) which automates the whole process.

Zookeeper, kafka and sample client start just fine, external kafka client defined in the test fails:
```
   00:19:52.090 [kafka-producer-network-thread | 07acefbb-3508-4512-be14-859dd7f6917d] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=07acefbb-3508-4512-be14-859dd7f6917d] Initiating connection to node 127.0.0.1:29092 (id: -1 rack: null)
    00:19:52.090 [kafka-producer-network-thread | 07acefbb-3508-4512-be14-859dd7f6917d] DEBUG org.apache.kafka.common.network.Selector - [Producer clientId=07acefbb-3508-4512-be14-859dd7f6917d] Connection with /127.0.0.1 disconnected
    java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:458)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:412)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163)
        at java.lang.Thread.run(Thread.java:748)
```

Could you please advise on why it doesn't work and what should be done to allow either internal (docker network) or external (host network) connections?

**Comment by tompizmor** [comment]
I could make external consumer and producer works with this configuration. 

```
version: "3"
services:
  kafka:
    hostname: 'kafka'
    image: 'bitnami/kafka:2.0.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:3.4.12'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
```

In order to test it I used the [kafkacat](https://github.com/edenhill/kafkacat) command.

**Run producer:**

```
kafkacat -b 127.0.0.1:9092 -P -t test
test
test2
test3
```

**Run consumer:**
```
kafkacat -b 127.0.0.1:9092 -C -t test
test
test2
test3
```

**Comment by denis-zhdanov** [comment]
Hello,

Thank you for responding. However, my question is not about configuring external clients, it's about configuring either internal (docker network) clients or external (host network) clients.

**Comment by tompizmor** [comment]
So you mean that you need to use both types of clients. You need to reach kafka from other docker containers and also from the host machine.

I will take another look tomorrow.

**Comment by tompizmor** [comment]
I tried now with this docker-compose:

```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      demo-net:
        ipv4_address: 172.40.0.5
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    networks:
      demo-net:
        ipv4_address: 172.40.0.6
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.6:9092
  consumer:
    image: 'bitnami/kafka:2'
    networks:
      demo-net:
        ipv4_address: 172.40.0.7
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.7:9092
  producer:
    image: 'bitnami/kafka:2'
    networks:
      demo-net:
        ipv4_address: 172.40.0.8
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.8:9092

networks:
  demo-net:
    ipam:
      config:
        - subnet: 172.40.0.5/16
```

The consumer and producer services from the docker-compose can reach kafka at the `kafka` hostname. These are acting as internal clients and can consume and produce messages:

Also, external clients can reach kafka at the IP 172.40.0.6

-----

**Internal producer command:**
`/opt/bitnami/kafka/bin/kafka-console-producer.sh --broker-list kafka:9092 --topic test`

**Internal consumer command:**
`/opt/bitnami/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning`

**External producer command:**
`kafkacat -b 172.40.0.6:9092 -P -t test`

**External consumer command:**
`kafkacat -b 172.40.0.6:9092 -C -t test`

**Comment by cricket007** [comment]
FWIW, see https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by juan131** [comment]
Great article @cricket007!! Thanks for sharing it!

**Comment by cricket007** [comment]
Tested on Mac with these settings

  ```yaml
ports:
 - 9092
 - 29092
environment:
 ...
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
  KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
```

Producer, outside of container

```bash
$ kafka-console-producer --broker-list localhost:29092 --topic test
>hello world
[2018-11-01 17:45:16,135] WARN Error while fetching metadata with correlation id 1 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2018-11-01 17:45:16,247] WARN Error while fetching metadata with correlation id 3 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
>sample
>text
>interesting
```

And consumer outside of container

```bash
$ kafka-console-consumer --bootstrap-server localhost:29092 --topic test --from-beginning
hello world
sample
text
interesting
^CProcessed a total of 4 messages
```
