### ISSUE TITLE
Kafka postinstallation error: symlink exists '/opt/bitnami/kafka/conf' -> '/opt/bitnami/kafka/config'

### ISSUE THREAD

**Issue by tgrzesik** [bitnami/bitnami-docker-kafka#45]
Hey,
I'm trying to run kafka cluster with bitnami helm chart (https://github.com/bitnami/charts/tree/master/bitnami/kafka) on bare-metal kubernetes with the following errors at runtime:
```
kafka   INFO  ==> No injected configuration files found. Creating default config files...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/kafka/conf' -> '/opt/bitnami/kafka/config'
```
I have tried with many tags (2.2.0, 2.0.0, 2.2.2-debian-r0, 1.1.1 etc.) with no result.

I found similar errors with apache (link to the issue: https://github.com/bitnami/bitnami-docker-opencart/issues/37). I'm using nfs-client persistencevolume type on my k8s cluster. Is it the same issue? It will be pretty hard to convince my team to change storage type just to make kafka work ;)

Any solutions or workarounds?

Thanks!

**Comment by marcosbc** [comment]
Hi @tgrzesik, it seems like you are not persisting the right directory or file.

You should be persisting `/bitnami/kafka`, but it seems like you might be persisting `/opt/bitnami/kafka/config`. Could you check if this is the case?

Also, if you're mounting any configuration file, you should be doing it from the directory `/opt/bitnami/kafka/conf` instead of `/opt/bitnami/kafka/config`.

**Comment by tgrzesik** [comment]
@marcosbc thanks for your fast reply.
I'm running on default statefulset config from helm chart. I don't think that's the issue especially when the same configuration on another k8s cluster works like a charm.

**Comment by marcosbc** [comment]
Hi @tgrzesik, unfortunately we don't know what could be happening in your case. Would you happen to know if the NFS disk is only being used for the persisted data volumes (`/bitnami`)?

The implementation of the Kafka initialization copies the contents of `config` to `conf`, then deletes the directory and finally creates a symlink (`config -> conf`).

Therefore, either `config` is not being deleted properly, or a configuration file was mounted in that directory.

Could you launch a new clean Helm chart with `image.debug` set to `true`? That should provide more info for debugging the issue on our side. Also, if you could provide your `values.yaml` file (hiding sensitive info) it would be great.

**Comment by jaskirat8** [comment]
I also faced same issue. But interesting thing is it worked on latest docker but for my server having docker Server Version: 17.09.0-ce this issue poped up.
I am not using any kind of data persistence and just raw same config(I am sure because one is staging and another is QA server for same code controlled by CI system)

Below is the compose file snapshot  :
```
services:
  zookeeper:
    deploy:
      mode: replicated
      replicas: 1
    environment:
      TZ: Asia/Kolkata
    image: zookeeper:3.5.5
  kafka:
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_BROKER_ID: '1'
      KAFKA_CFG_HOST_NAME: kafka
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      TZ: Asia/Kolkata
    image: bitnami/kafka:2.2.1
```

**Comment by marcosbc** [comment]
Hi @jaskirat8, we were able to get it working with the following `docker-compose.yml` file:

```
version: '2'

services:
  zookeeper:
    image: zookeeper:3.5.5
  kafka:
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_HOST_NAME=kafka
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    image: bitnami/kafka:2.2.1
```

Note that we are using the latest release of `bitnami/kafka:2.2.1` which is `8f763c50` (or `bitnami/kafka:2.2.1-debian-9-r22`).

In recent releases we changed the approach of how the Kafka container works. Could you verify your Kafka image is updated?
