### ISSUE TITLE
Change max.poll.interval.ms property 

### ISSUE THREAD

**Issue by tguless** [bitnami/bitnami-docker-kafka#46]
I need to change  max.poll.interval.ms property to troubleshoot an issue I am encountering similar to the one discussed here: 

https://stackoverflow.com/questions/53292655/spring-kafka-always-rebalance-after-5-min-even-i-pause-consumer

What is the best way to go about this?

**Comment by tompizmor** [comment]
Hi @tguless,

Right now there is no available environment variable to configure `max.poll.interval.ms`. However, we are working on a generic way to set Kafka settings by mapping env vars to configuration values that will be ready soon.

In the meantime, maybe you can connect to the container before Kafka is initialized and edit the template for the configuration file adding the value you are interested in. To do so, please follow this steps:

1. Edit docker-compose to override the default entrypoint:
```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    command: tail -f /dev/null
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

2. Run `docker-compose up` and exec into the kafka container to edit the config file located at `/opt/bitnami/kafka/configtmp/server.properties`. (You will need to install a file editor)
3. Initialize kafka running the command `/app-entrypoint.sh /run.sh`
