### ISSUE TITLE
any example for  BROKER_ID_COMMAND ?

### ISSUE THREAD

**Issue by ludurr** [bitnami/bitnami-docker-kafka#47]
Hi,
i have replace the KAFKA_BROKER_ID="" with an empty string and trying to provide an   ordinal  from statefulset, but I cannot get result.
Can you have look please.

Thank you

`- name: KAFKA_BROKER_ID
    value: ""
 - name: BROKER_ID_COMMAND
    value: hostname | awk -F '-' '{print $2}'`

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about where you are setting these values?

**Comment by he2ss** [comment]
Hi,

I use also this image in statefulset. With this, it will provide you the ID in relation the POD:

```
containers:
      - env:
        - name: BROKER_ID_COMMAND
          value: "${HOSTNAME##*-}"
```
