### ISSUE TITLE
Kafka Broker stops when SASL listeners is enabled

### ISSUE THREAD

**Issue by sathisz** [bitnami/bitnami-docker-kafka#5]
I am using latest image. When I enabled the SASL listeners in Kafka broker it stops. It's unable to find the kafka_jass.conf file.
Below is the output I get and then kafka broker stops.
```
kafka_broker_1 | Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
kafka_broker_1 | 	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
kafka_broker_1 | 	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
kafka_broker_1 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
kafka_broker_1 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
kafka_broker_1 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
kafka_broker_1 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
kafka_broker_1 | 	at java.lang.Class.newInstance(Class.java:442)
kafka_broker_1 | 	at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
kafka_broker_1 | 	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
kafka_broker_1 | 	at java.security.AccessController.doPrivileged(Native Method)
kafka_broker_1 | 	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
kafka_broker_1 | 	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:40)
kafka_broker_1 | 	... 5 more
kafka_broker_1 | [2017-10-27 05:34:38,936] INFO shutting down (kafka.server.KafkaServer)
kafka_broker_1 | [2017-10-27 05:34:38,941] INFO shut down completed (kafka.server.KafkaServer)
```

I tried to find the kafka_jaas.conf file inside the container, But the file is unavailable.

**Comment by juan131** [comment]
Hello @sathisz 

I was unable to reproduce the issue. I added the environment variables below to the "services->kafka->environment" section in the `docker.compose.yml` file as it's described in the Documentation (https://github.com/bitnami/bitnami-docker-kafka#security):

```
      - KAFKA_LISTENERS=SASL_SSL://:9092
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092
```

Then, I run `docker-compose up` and both services (zookeeper and kafka) were started without any issue. I also connected to the Kafka broker and I did find the `kafka_jaas.conf` file:

```
$ docker exec -it bitnamidockerkafka_kafka_1 bash
$ find /bitnami/kafka/ -name "kafka_jaas.conf*"
/bitnami/kafka/conf/kafka_jaas.conf
```

**Comment by bagaliu** [comment]
Hi @juan131 , I can reproduce the same error as @sathisz. In the same time, I try to set KAFKA_ADVERTISED_HOST_NAME and KAFKA_ZOOKEEPER_CONNECT, but neither them work. The server.properties didn't change after I change these value in my docker-compose.ym

**Comment by juan131** [comment]
Hi @bagaliu ! I am unable to reproduce it. Could you share the `docker-compose.yml` you are using?

**Comment by sathisz** [comment]
Hello @juan131 .Try with two listeners.
`KAFKA_LISTENERS=SASL_SSL://:9092,SSL://9093
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092,SSL://9093`

While using two listeners I encountered the issue

**Comment by tompizmor** [comment]
Hello @sathisz,

I am not able to reproduce the issue either. I think that maybe the configuration is being persisted in the volume and that's why you are experiencing the issue.
Would you mind trying the following?

1. First of all, use this docker-compose file:

```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=SASL_SSL://:9092
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

2. Clean the environment. Just in case there are named volumes with persisted configuration.

```
$ docker-compose down -v  
```

3. Deploy the kafka-zookeeper servers

```
$ docker-compose up
```
4. Exec into the kafka container

```
docker-compose exec kafka bash
```

5. Look for jaas file:

```
ls /opt/bitnami/kafka/conf/kafka_jaas.conf
```

Please let me know if this helps!

**Comment by sathisz** [comment]
The conf file exists for Plain auth, If we enabled SSL auth, there is no conf file. Please try the below docker compose the file. Let me know if you encountered the same issue I faced.
```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=SASL_SSL://:9092, SSL://9093
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092, SSL://9093

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

**Comment by tompizmor** [comment]
Hello @sathisz,

There was a typo in your docker-compose file. You were missing the colons before the port in the SSL listeners.

This:

```
      - KAFKA_LISTENERS=SASL_SSL://:9092, SSL://9093
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092, SSL://9093
```

should be:

```
      - KAFKA_LISTENERS=SASL_SSL://:9092, SSL://:9093
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092, SSL://:9093
```


So using this docker-compose file worked fine for me:

```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=SASL_SSL://:9092, SSL://9093
      - KAFKA_ADVERTISED_LISTENERS=SASL_SSL://:9092, SSL://9093

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

Could you give it a try?
