### ISSUE TITLE
Problem of using SASL_PLAINTEXT

### ISSUE THREAD

**Issue by hosuike** [bitnami/bitnami-docker-kafka#57]
I am creating a simple Kafka configuration using docker-compose:
- one zookeeper, one kafka
- users need user/password to connect to kafka topic (using paas.conf file)
- No need to use SSL, nor zookeeper password 

Here is the docker-compose:
```
version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - network

  kafka:
    image: bitnami/kafka:2
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERES=SASL_PLAINTEXT://192.168.0.101:9092
      - KAFKA_BROKER_USER=admin
      - KAFKA_BROKER_PASSWORD=password
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - network

networks:
  network:
```
192.168.0.101 is IP address of my desktop.

The log output shows:
```
kafka_1      | [2019-07-11 16:08:17,013] INFO KafkaConfig values:
kafka_1      |  advertised.host.name = null
kafka_1      |  advertised.listeners = PLAINTEXT://:9092
kafka_1      |  advertised.port = null
```
The advertised listener is not able to pick up from environment variable.

**Comment by tompizmor** [comment]
Hello @hosuike,

There is a typo in your configuration. The environment variable `KAFKA_CFG_ADVERTISED_LISTENERES` should be called `KAFKA_CFG_ADVERTISED_LISTENERS`.

I used your docker-compose to launch Kafka, exec into the container and check the environment:

```
KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
KAFKA_CFG_ADVERTISED_LISTENERES=SASL_PLAINTEXT://192.168.0.101:9092
```

As you can see, Kafka is getting the value from `KAFKA_CFG_ADVERTISED_LISTENERS` and ignoring `KAFKA_CFG_ADVERTISED_LISTENERES`

**Comment by hosuike** [comment]
Well it's embarrassing...okay here is the docker-compose will be work:
```
version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - network

  kafka:
    image: bitnami/kafka:2
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://192.168.0.101:9092
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_USER=ibadmin
      - KAFKA_INTER_BROKER_PASSWORD=password
      - KAFKA_BROKER_USER=admin
      - KAFKA_BROKER_PASSWORD=password
      ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - network

networks:
  network:
```

Okay I have another question about the inter-broker security.  As this is one-zookeeper-one-kafka-broker config, I think I don't really need to setup inter-broker security.  My requirement is to secure the kafka topic with username / password only.  So it's possible to turn off the inter-broker security ?
