### ISSUE TITLE
zkCli => Unable to read additional data from server

### ISSUE THREAD

**Issue by ssi-anik** [bitnami/bitnami-docker-kafka#67]
I am new to kafka. I tried using your kafka & zookeeper images. my docker-compose looks like following.
```
zookeeper:
    image: bitnami/zookeeper:3.5.5
    ports:
        - 2181:2181
    environment:
        - ZOO_ENABLE_AUTH=yes
        - ZOO_CLIENT_USER=kafka
        - ZOO_CLIENT_PASSWORD=kafka_password
    volumes:
        - ~/.backup/zookeeper/kafka-php:/bitnami/zookeeper

kafka:
    build: ./docker/kafka/
    ports:
        - 9092:9092
    links:
        - zookeeper
    depends_on:
        - zookeeper
    environment:
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ZOOKEEPER_USER=kafka
        - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
    volumes:
        - ~/.backup/kafka/kafka-php:/bitnami/kafka
```

**Steps to reproduce the issue:**
When I exec my container, and run `zkCli.sh -server localhost:2181` I find the following output for the above configuration.
![zkcli-error-w-auth](https://user-images.githubusercontent.com/2676602/65984111-dc186f80-e4a0-11e9-8e3c-27c4a3229b1d.png)

But when I set my container's environment variable to `ALLOW_ANONYMOUS_LOGIN=yes` and I run the above command, I find no warning like the attached image. Or if I copy the docker-compose file as of your repository, I find no issue. 
![zkcli-no-issue](https://user-images.githubusercontent.com/2676602/65984491-b50e6d80-e4a1-11e9-9c9f-d7d89c62cf54.png)

Am I doing anything wrong?

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 92
 Running: 3
 Paused: 0
 Stopped: 89
Images: 258
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.0.0-27-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: sirajul
ID: NOJG:KUSW:HVIO:TIYT:TLZT:QKLE:6GTN:7T6I:RHMX:THY6:54LH:PXOL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sirajul
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

TIA.
