### ISSUE TITLE
Add Docker HEALTHCHECK

### ISSUE THREAD

**Issue by vanthome** [bitnami/bitnami-docker-kafka#68]
Hi, this is a feature request.
Docker has a feature `HEALTHCHECK` which can tell docker the healthiness of a service given that you put a proper health check command behind it.

The feature is documented here: https://docs.docker.com/engine/reference/builder/
BG, Thomas

**Comment by miguelaeh** [comment]
Hi @vanthome ,
Thank you very much for the information, we already evaluated this and we plan to add it. We will update this thread in the future with the news.

**Comment by vanthome** [comment]
Activity :)

**Comment by adison88** [comment]
until you add it, how'd you guys recommend to tackle it?

**Comment by dani8art** [comment]
Hi, 

From my point of view, there are two ways to tackle it:

1. If you are using a docker command to run the container, I mean you are running it by executing `docker run`, you have to extend the image using `FROM` tag then you have to build a new image. 

```
FROM bitnami/kafka:2.4.0-r13

USER root
RUN install_packages net-tools
USER 1001

HEALTHCHECK CMD netstat -an | grep 9092 > /dev/null; if [ 0 != $? ]; then exit 1; fi;
```

2. If you are using docker-compose to run the container you can use this https://docs.docker.com/compose/compose-file/#healthcheck 

```
version: "2.1" # Note you should use 2.1 or up

services:
  zookeeper:
    image: "bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:2"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```
