### ISSUE TITLE
The cluster is reachable but kafka can't connect.

### ISSUE THREAD

**Issue by Mds92** [bitnami/bitnami-docker-kafka#83]
I installed `bitnami/kafka:latest` with the following compose yaml file on an Ubuntu 18.0.4 VM:

```yaml
version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
```

Now I want to connect to my Kafka with https://www.conduktor.io/
I can connect to zookeeper with it successfully but I can not connect to Kafka with the following error:
> The cluster is reachable but Kafka can't connect. Check if you have access to the advertised host names to the cluster and the authorizations.

How should I config 'bitnami/kafka:latest' to connect externally to it?

**Comment by marcosbc** [comment]
@Mds92 We're assuming that you are running Conduktor in the host machine, while Kafka is running in the Ubuntu 18.04 VM. In this case, did you check your Ubuntu 18.04 VM firewall settings?

Note that when running the following command in the host, you should get a similar result (replacing [ubuntu vm ip address] with an appropriate value):

```
$ curl [ubuntu vm ip address]:9092
curl: (56) Recv failure: Connection reset by peer
```

If you get a timeout it is most likely happening because of there being a firewall blocking connections, in which case you should allow it to listen to connections to port 9092.

If it works, note that you should configure Conduktor to use the Ubuntu VM IP address. Note that `KAFKA_ADVERTISED_LISTENERS` must match that value if not left empty (such as `PLAINTEXT://:9092`).

**Comment by hamster1979** [comment]
Similar situation. firewall disabled at all. Kafka accessible - 
```
curl kafka-container-ip:9092  
curl: (52) Empty reply from server
```
Conduktor connection to zookeeper ok, connection to kafka "The cluster is reachable but Kafka can't connect ...". In logs of kafka - nothing

**Comment by Mds92** [comment]
I done it.

Test Kafka from my WIndows 10:
```
C:\WINDOWS\system32>curl 192.168.179.133:9092
curl: (56) Recv failure: Connection was reset
```
Test ZK is OK
Also, I set Kafka Bootstrap  Servers as 192.168.179.133:9092, but the following error occured
`
Conduktor connection to zookeeper ok, connection to kafka "The cluster is reachable but Kafka can't connect ...
`

**Comment by hamster1979** [comment]
> I done it.
> 
> Test Kafka from my Windows 10:
> 
> ```
> C:\WINDOWS\system32>curl 192.168.179.133:9092
> curl: (56) Recv failure: Connection was reset
> ```
> 
> Test ZK is OK
> Also, I set Kafka Bootstrap Servers as 192.168.179.133:9092, but the following error occured
> `Conduktor connection to zookeeper ok, connection to kafka "The cluster is reachable but Kafka can't connect ...`

try Kafka Tool, not Conduktor. this may be Conduktor issue, not kafka

**Comment by hamster1979** [comment]
with this 
```
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL 
```
i had 
```
user@user-PC:~/kafka$ kafkacat -b external-kafka-dname:12092 -L
Metadata for all topics (from broker -1: external-kafka-dname:12092/bootstrap):
 1 brokers:
  broker 1001 at localhost:9092
 0 topics:
```
but Gui kafka tool and Conduktor steel the same error.

**Comment by hamster1979** [comment]
@Mds92 i'm done. This config is ok:
```
version: '2'

services:
  zookeeper:
    networks:
      - kafka-net
    image: 'bitnami/zookeeper:3'
    ports:
      - '12181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'      
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_TICK_TIME=4000     
  kafka:
    networks:
      - kafka-net  
    image: 'bitnami/kafka:2'
    ports:
      - '12092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://external_kafka_url:12092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL 
    depends_on:
      - zookeeper
      
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

**Comment by Mds92** [comment]
@hamster1979 
I've done it and tested with Kafka Tool 2.0.7 and Conduktor.
Test of ZK is OK. but to test Kafka, the same error in Conduktor and the following error in Kafka Tool
```
Error connecting to the cluster. Timeout connection to broker(s). bootrstap.servers=192.168.179.133:12092
```
P.S:
I'm using VMware workstation 15.5.1 with Ubuntu 18.0.4

**Comment by hamster1979** [comment]
@Mds92 this mean that your have  wrong config . Its necessary to add this lines:
```
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://external_kafka_url:12092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL 
```
where 12092 is exposed port to 9092 internal port. external_kafka_url - external address of kafka container.

**Comment by Mds92** [comment]
I tested with the following compose-file:
```yaml
version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    networks:
      - kafka-net
    image: 'bitnami/zookeeper:3'
    ports:
      - '12181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'      
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_TICK_TIME=4000     
  kafka:
    networks:
      - kafka-net  
    image: 'bitnami/kafka:2'
    ports:
      - '12092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9093,EXTERNAL://:12092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL 
    depends_on:
      - zookeeper
      
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```
