### ISSUE TITLE
Cannot connect to Kafka with SASL_PLAINTEXT

### ISSUE THREAD

**Issue by aldialimucaj** [bitnami/bitnami-docker-kafka#87]
I am using the latest or v2.4.0.
I have configured kafka to use plain authentication without ssl but it does not work. When i try to consume messages following warning appears:

`WARN [Consumer clientId=consumer-console-consumer-16912-1, groupId=console-consumer-16912] Connection to node -1 (localhost/127.0.0.1:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient)`

The producers looks like connected but goes into timeout with following error

`ERROR Error when sending message to topic gps_data with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)`

Here is me docker compose file
```

 version: '3'

 services:
   zookeeper:
     image: 'bitnami/zookeeper:3'
     ports:
       - '2182:2181'
     hostname: zookeeper
     networks:
         - backend
     volumes:
       - 'zookeeper_data:/bitnami'
     environment:
       - ALLOW_ANONYMOUS_LOGIN=yes
   kafka:
     image: 'bitnami/kafka:2'
     depends_on:
       -  zookeeper
     ports:
       - '9092:9092'
     hostname: 'host1'
     networks:
         - kafka
         - backend
     volumes:
       - 'kafka_data:/bitnami'
     environment:
       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://host1:9092
       - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://host1:9092
     depends_on:
       - zookeeper

 networks:
      backend:
         external:
             name: backend
      kafka:
         external:
             name: kafka
 volumes:
   zookeeper_data:
     driver: local
     driver_opts:
         type: none
         o: bind,rw
         device: $PWD/zookeeper_data
   kafka_data:
     driver: local
     driver_opts:
         type: none
         o: bind,rw
         device: $PWD/kafka_data


```

My jaas config for the cli looks like

```
KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="user"
  password="bitnami";
};
```

and my consumer/producer config properties looks like
```

security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
```
